// Copyright 2026 The Go Language Server Authors.
// SPDX-License-Identifier: BSD-3-Clause

// Command lspgen generates Go types for the Language Server Protocol.
package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"maps"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"slices"
	"strconv"
	"strings"
	"sync"

	"github.com/go-json-experiment/json"
	"github.com/go-json-experiment/json/jsontext"
	gofumpt "mvdan.cc/gofumpt/format"
)

// Go port of microsoft/typescript-go/internal/lsp/lsproto/_generate/generate.mts.

// generatedHeader is prepended to generated protocol files.
const generatedHeader = `// Copyright 2026 The Go Language Server Authors.
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by lspgen.go; DO NOT EDIT.

`

// OrderedMap preserves insertion order for string keys.
type OrderedMap[V any] struct {
	keys   []string
	values map[string]V
}

// NewOrderedMap returns an empty OrderedMap.
func NewOrderedMap[V any]() *OrderedMap[V] {
	return &OrderedMap[V]{
		values: make(map[string]V),
	}
}

// Set stores a key/value pair and tracks insertion order.
func (m *OrderedMap[V]) Set(key string, value V) {
	if _, ok := m.values[key]; !ok {
		m.keys = append(m.keys, key)
	}
	m.values[key] = value
}

// Get returns the value for key and whether it exists.
func (m *OrderedMap[V]) Get(key string) (V, bool) {
	v, ok := m.values[key]
	return v, ok
}

// Keys returns a copy of the keys in insertion order.
func (m *OrderedMap[V]) Keys() []string {
	return append([]string(nil), m.keys...)
}

// Schema types.

// BaseTypes represents schema base types.
type BaseTypes string

// MessageDirection represents schema message directions.
type MessageDirection string

// TypeKind identifies the kind of a schema type node.
type TypeKind string

const (
	kindBase           TypeKind = "base"
	kindReference      TypeKind = "reference"
	kindArray          TypeKind = "array"
	kindMap            TypeKind = "map"
	kindAnd            TypeKind = "and"
	kindOr             TypeKind = "or"
	kindTuple          TypeKind = "tuple"
	kindLiteral        TypeKind = "literal"
	kindStringLiteral  TypeKind = "stringLiteral"
	kindIntegerLiteral TypeKind = "integerLiteral"
	kindBooleanLiteral TypeKind = "booleanLiteral"
)

// Type describes a schema type node.
type Type struct {
	Kind    TypeKind `json:"kind"`
	Name    string   `json:"name,omitzero"`
	Items   []*Type  `json:"items,omitzero"`
	Key     *Type    `json:"key,omitzero"`
	Value   *Type    `json:"value,omitzero"`
	Element *Type    `json:"element,omitzero"`

	Literal      *StructureLiteral
	StringValue  *string
	IntegerValue *int
	BoolValue    *bool
}

// rawType is the JSON wire representation of Type.
type rawType struct {
	Kind    TypeKind       `json:"kind"`
	Name    string         `json:"name,omitzero"`
	Items   []*Type        `json:"items,omitzero"`
	Key     *Type          `json:"key,omitzero"`
	Value   jsontext.Value `json:"value,omitzero"`
	Element *Type          `json:"element,omitzero"`
}

// UnmarshalJSON decodes a Type with kind-aware value handling.
func (t *Type) UnmarshalJSON(data []byte) error {
	var raw rawType
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	t.Kind = raw.Kind
	t.Name = raw.Name
	t.Items = raw.Items
	t.Key = raw.Key
	t.Element = raw.Element

	switch raw.Kind {
	case kindMap:
		if len(raw.Value) > 0 {
			var val Type
			if err := json.Unmarshal(raw.Value, &val); err != nil {
				return err
			}
			t.Value = &val
		}

	case kindLiteral:
		if len(raw.Value) > 0 {
			var lit StructureLiteral
			if err := json.Unmarshal(raw.Value, &lit); err != nil {
				return err
			}
			t.Literal = &lit
		}

	case kindStringLiteral:
		var v string
		if err := json.Unmarshal(raw.Value, &v); err != nil {
			return err
		}
		t.StringValue = &v

	case kindIntegerLiteral:
		var v int
		if err := json.Unmarshal(raw.Value, &v); err != nil {
			return err
		}
		t.IntegerValue = &v

	case kindBooleanLiteral:
		var v bool
		if err := json.Unmarshal(raw.Value, &v); err != nil {
			return err
		}
		t.BoolValue = &v

	default:
		if len(raw.Value) > 0 {
			// ignore
		}
	}

	return nil
}

// Property describes a structure field in the meta model.
type Property struct {
	Name          string   `json:"name"`
	Type          *Type    `json:"type"`
	Optional      bool     `json:"optional,omitzero"`
	Documentation string   `json:"documentation,omitzero"`
	Since         string   `json:"since,omitzero"`
	SinceTags     []string `json:"sinceTags,omitzero"`
	Proposed      bool     `json:"proposed,omitzero"`
	Deprecated    string   `json:"deprecated,omitzero"`
	OmitzeroValue bool     `json:"omitzeroValue,omitzero"`
}

// Structure describes a named schema structure.
type Structure struct {
	Name          string     `json:"name"`
	Extends       []*Type    `json:"extends,omitzero"`
	Mixins        []*Type    `json:"mixins,omitzero"`
	Properties    []Property `json:"properties"`
	Documentation string     `json:"documentation,omitzero"`
	Since         string     `json:"since,omitzero"`
	SinceTags     []string   `json:"sinceTags,omitzero"`
	Proposed      bool       `json:"proposed,omitzero"`
	Deprecated    string     `json:"deprecated,omitzero"`
}

// StructureLiteral describes an inline object type.
type StructureLiteral struct {
	Properties    []Property `json:"properties"`
	Documentation string     `json:"documentation,omitzero"`
	Since         string     `json:"since,omitzero"`
	SinceTags     []string   `json:"sinceTags,omitzero"`
	Proposed      bool       `json:"proposed,omitzero"`
	Deprecated    string     `json:"deprecated,omitzero"`
}

// TypeAlias defines a named alias for a schema type.
type TypeAlias struct {
	Name string `json:"name"`
	Type *Type  `json:"type"`
}

// Enumeration defines a named enumeration.
type Enumeration struct {
	Name                 string      `json:"name"`
	Type                 *Type       `json:"type"`
	Values               []EnumEntry `json:"values"`
	SupportsCustomValues bool        `json:"supportsCustomValues,omitzero"`
	Documentation        string      `json:"documentation,omitzero"`
	Since                string      `json:"since,omitzero"`
	SinceTags            []string    `json:"sinceTags,omitzero"`
	Proposed             bool        `json:"proposed,omitzero"`
	Deprecated           string      `json:"deprecated,omitzero"`
}

// EnumEntry describes a single enumeration value.
type EnumEntry struct {
	Name          string `json:"name"`
	ValueRaw      any    `json:"value"`
	Documentation string `json:"documentation,omitzero"`
	Deprecated    string `json:"deprecated,omitzero"`
}

// MetaData carries meta model versioning information.
type MetaData struct {
	Version string `json:"version"`
}

// MetaModel is the root schema model for code generation.
type MetaModel struct {
	MetaData      MetaData       `json:"metaData"`
	Requests      []Request      `json:"requests"`
	Notifications []Notification `json:"notifications"`
	Structures    []Structure    `json:"structures"`
	Enumerations  []Enumeration  `json:"enumerations"`
	TypeAliases   []TypeAlias    `json:"typeAliases"`
}

// Request describes a protocol request entry in the meta model.
type Request struct {
	Method              string `json:"method"`
	TypeName            string `json:"typeName,omitzero"`
	paramsRaw           jsontext.Value
	Params              *Type    `json:"-"`
	ParamsArray         []*Type  `json:"-"`
	Result              *Type    `json:"result"`
	PartialResult       *Type    `json:"partialResult,omitzero"`
	ErrorData           *Type    `json:"errorData,omitzero"`
	RegistrationMethod  string   `json:"registrationMethod,omitzero"`
	RegistrationOptions *Type    `json:"registrationOptions,omitzero"`
	MessageDirection    string   `json:"messageDirection"`
	Documentation       string   `json:"documentation,omitzero"`
	Since               string   `json:"since,omitzero"`
	SinceTags           []string `json:"sinceTags,omitzero"`
	Proposed            bool     `json:"proposed,omitzero"`
	Deprecated          string   `json:"deprecated,omitzero"`
}

// UnmarshalJSON decodes Request params that may be an object or array.
func (r *Request) UnmarshalJSON(data []byte) error {
	var aux struct {
		Method              string         `json:"method"`
		TypeName            string         `json:"typeName,omitzero"`
		ParamsRaw           jsontext.Value `json:"params,omitzero"`
		Result              *Type          `json:"result"`
		PartialResult       *Type          `json:"partialResult,omitzero"`
		ErrorData           *Type          `json:"errorData,omitzero"`
		RegistrationMethod  string         `json:"registrationMethod,omitzero"`
		RegistrationOptions *Type          `json:"registrationOptions,omitzero"`
		MessageDirection    string         `json:"messageDirection"`
		Documentation       string         `json:"documentation,omitzero"`
		Since               string         `json:"since,omitzero"`
		SinceTags           []string       `json:"sinceTags,omitzero"`
		Proposed            bool           `json:"proposed,omitzero"`
		Deprecated          string         `json:"deprecated,omitzero"`
	}
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	*r = Request{
		Method:              aux.Method,
		TypeName:            aux.TypeName,
		paramsRaw:           aux.ParamsRaw,
		Result:              aux.Result,
		PartialResult:       aux.PartialResult,
		ErrorData:           aux.ErrorData,
		RegistrationMethod:  aux.RegistrationMethod,
		RegistrationOptions: aux.RegistrationOptions,
		MessageDirection:    aux.MessageDirection,
		Documentation:       aux.Documentation,
		Since:               aux.Since,
		SinceTags:           aux.SinceTags,
		Proposed:            aux.Proposed,
		Deprecated:          aux.Deprecated,
	}

	if len(aux.ParamsRaw) > 0 {
		switch aux.ParamsRaw[0] {
		case '[':
			var arr []*Type
			if err := json.Unmarshal(aux.ParamsRaw, &arr); err != nil {
				return err
			}
			r.ParamsArray = arr

		default:
			var t Type
			if err := json.Unmarshal(aux.ParamsRaw, &t); err != nil {
				return err
			}
			r.Params = &t
		}
	}

	return nil
}

// Notification describes a protocol notification entry in the meta model.
type Notification struct {
	Method              string `json:"method"`
	TypeName            string `json:"typeName,omitzero"`
	paramsRaw           jsontext.Value
	Params              *Type    `json:"-"`
	ParamsArray         []*Type  `json:"-"`
	RegistrationMethod  string   `json:"registrationMethod,omitzero"`
	RegistrationOptions *Type    `json:"registrationOptions,omitzero"`
	MessageDirection    string   `json:"messageDirection"`
	Documentation       string   `json:"documentation,omitzero"`
	Since               string   `json:"since,omitzero"`
	SinceTags           []string `json:"sinceTags,omitzero"`
	Proposed            bool     `json:"proposed,omitzero"`
	Deprecated          string   `json:"deprecated,omitzero"`
}

// UnmarshalJSON decodes Notification params that may be an object or array.
func (n *Notification) UnmarshalJSON(data []byte) error {
	var aux struct {
		Method              string         `json:"method"`
		TypeName            string         `json:"typeName,omitzero"`
		ParamsRaw           jsontext.Value `json:"params,omitzero"`
		RegistrationMethod  string         `json:"registrationMethod,omitzero"`
		RegistrationOptions *Type          `json:"registrationOptions,omitzero"`
		MessageDirection    string         `json:"messageDirection"`
		Documentation       string         `json:"documentation,omitzero"`
		Since               string         `json:"since,omitzero"`
		SinceTags           []string       `json:"sinceTags,omitzero"`
		Proposed            bool           `json:"proposed,omitzero"`
		Deprecated          string         `json:"deprecated,omitzero"`
	}
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}

	*n = Notification{
		Method:              aux.Method,
		TypeName:            aux.TypeName,
		paramsRaw:           aux.ParamsRaw,
		RegistrationMethod:  aux.RegistrationMethod,
		RegistrationOptions: aux.RegistrationOptions,
		MessageDirection:    aux.MessageDirection,
		Documentation:       aux.Documentation,
		Since:               aux.Since,
		SinceTags:           aux.SinceTags,
		Proposed:            aux.Proposed,
		Deprecated:          aux.Deprecated,
	}

	if len(aux.ParamsRaw) > 0 {
		switch aux.ParamsRaw[0] {
		case '[':
			var arr []*Type
			if err := json.Unmarshal(aux.ParamsRaw, &arr); err != nil {
				return err
			}
			n.ParamsArray = arr

		default:
			var t Type
			if err := json.Unmarshal(aux.ParamsRaw, &t); err != nil {
				return err
			}
			n.Params = &t
		}
	}

	return nil
}

var customStructures = []Structure{
	{
		Name: "InitializationOptions",
		Properties: []Property{
			{
				Name: "disablePushDiagnostics",
				Type: &Type{
					Name: "boolean",
					Kind: kindBase,
				},
				Optional:      true,
				Documentation: "DisablePushDiagnostics disables automatic pushing of diagnostics to the client.",
			},
		},
		Documentation: "InitializationOptions contains user-provided initialization options.",
	},
	{
		Name: "ExportInfoMapKey",
		Properties: []Property{
			{
				Name:          "symbolName",
				Documentation: "The symbol name.",
				Type: &Type{
					Name: "string",
					Kind: kindBase,
				},
				OmitzeroValue: true,
			},
			{
				Name:          "symbolId",
				Documentation: "The symbol ID.",
				Type: &Type{
					Name: "uint64",
					Kind: kindReference,
				},
				OmitzeroValue: true,
			},
			{
				Name:          "ambientModuleName",
				Documentation: "The ambient module name.",
				Type: &Type{
					Name: "string",
					Kind: kindBase,
				},
				OmitzeroValue: true,
			},
			{
				Name:          "moduleFile",
				Documentation: "The module file path.",
				Type: &Type{
					Name: "string",
					Kind: kindBase,
				},
				OmitzeroValue: true,
			},
		},
		Documentation: "ExportInfoMapKey uniquely identifies an export for auto-import purposes.",
	},
	{
		Name: "AutoImportData",
		Properties: []Property{
			{
				Name:          "exportName",
				Documentation: "The name of the property or export in the module's symbol table. Differs from the completion name in the case of InternalSymbolName.ExportEquals and InternalSymbolName.Default.",
				Type: &Type{
					Name: "string",
					Kind: kindBase,
				},
				OmitzeroValue: true,
			},
			{
				Name:          "exportMapKey",
				Documentation: "The export map key for this auto-import.",
				Type: &Type{
					Name: "ExportInfoMapKey",
					Kind: kindReference,
				},
				OmitzeroValue: true,
			},
			{
				Name:          "moduleSpecifier",
				Documentation: "The module specifier for this auto-import.",
				Type: &Type{
					Name: "string",
					Kind: kindBase,
				},
				OmitzeroValue: true,
			},
			{
				Name:          "fileName",
				Documentation: "The file name declaring the export's module symbol, if it was an external module.",
				Type: &Type{
					Name: "string",
					Kind: kindBase,
				},
				OmitzeroValue: true,
			},
			{
				Name:          "ambientModuleName",
				Documentation: "The module name (with quotes stripped) of the export's module symbol, if it was an ambient module.",
				Type: &Type{
					Name: "string",
					Kind: kindBase,
				},
				OmitzeroValue: true,
			},
			{
				Name:          "isPackageJsonImport",
				Documentation: "True if the export was found in the package.json AutoImportProvider.",
				Type: &Type{
					Name: "boolean",
					Kind: kindBase,
				},
				OmitzeroValue: true,
			},
		},
		Documentation: "AutoImportData contains information about an auto-import suggestion.",
	},
	{
		Name: "CompletionItemData",
		Properties: []Property{
			{
				Name:          "fileName",
				Documentation: "The file name where the completion was requested.",
				Type: &Type{
					Name: "string",
					Kind: kindBase,
				},
				OmitzeroValue: true,
			},
			{
				Name:          "position",
				Documentation: "The position where the completion was requested.",
				Type: &Type{
					Name: "integer",
					Kind: kindBase,
				},
				OmitzeroValue: true,
			},
			{
				Name:          "source",
				Documentation: "Special source value for disambiguation.",
				Type: &Type{
					Name: "string",
					Kind: kindBase,
				},
				OmitzeroValue: true,
			},
			{
				Name:          "name",
				Documentation: "The name of the completion item.",
				Type: &Type{
					Name: "string",
					Kind: kindBase,
				},
				OmitzeroValue: true,
			},
			{
				Name:          "autoImport",
				Documentation: "Auto-import data for this completion item.",
				Type: &Type{
					Name: "AutoImportData",
					Kind: kindReference,
				},
				Optional: true,
			},
		},
		Documentation: "CompletionItemData is preserved on a CompletionItem between CompletionRequest and CompletionResolveRequest.",
	},
}

var (
	explicitDataStructuresOnce sync.Once
	explicitDataStructuresMap  map[string]struct{}
)

// explicitDataStructures returns the set of custom data structures defined upfront.
func explicitDataStructures() map[string]struct{} {
	explicitDataStructuresOnce.Do(func() {
		m := make(map[string]struct{}, len(customStructures))
		for _, s := range customStructures {
			m[s.Name] = struct{}{}
		}
		explicitDataStructuresMap = m
	})

	return explicitDataStructuresMap
}

var registerOptionsUnionType *Type

// patchAndPreprocessModel normalizes the model and injects synthesized structures.
func patchAndPreprocessModel(model *MetaModel) error {
	// Collect all registration options so we can normalize "and" unions later.
	// Keep direct pointers so replacements update the original model nodes in-place.
	registrationOptionTypes := []*Type{}
	for i := range model.Requests {
		if model.Requests[i].RegistrationOptions != nil {
			registrationOptionTypes = append(registrationOptionTypes, model.Requests[i].RegistrationOptions)
		}
	}
	for i := range model.Notifications {
		if model.Notifications[i].RegistrationOptions != nil {
			registrationOptionTypes = append(registrationOptionTypes, model.Notifications[i].RegistrationOptions)
		}
	}

	syntheticStructures := []Structure{}
	for i, regOptType := range registrationOptionTypes {
		if regOptType == nil || regOptType.Kind != kindAnd {
			continue
		}

		// Find the request/notification that owns this registration options type.
		// The schema does not name "and" unions, so the owner drives naming and docs.
		var ownerMethod string
		var ownerTypeName string
		for idx := range model.Requests {
			if model.Requests[idx].RegistrationOptions == regOptType {
				ownerMethod = model.Requests[idx].Method
				ownerTypeName = model.Requests[idx].TypeName
				break
			}
		}
		if ownerMethod == "" {
			for idx := range model.Notifications {
				if model.Notifications[idx].RegistrationOptions == regOptType {
					ownerMethod = model.Notifications[idx].Method
					ownerTypeName = model.Notifications[idx].TypeName
					break
				}
			}
		}
		if ownerMethod == "" {
			return errors.New("could not find owner for 'and' type registration option")
		}

		// Derive a stable synthesized name from the request/notification identity.
		var structureName string
		if ownerTypeName != "" {
			structureName = strings.TrimSuffix(strings.TrimSuffix(ownerTypeName, "Request"), "Notification") + "RegistrationOptions"
		} else {
			parts := strings.Split(ownerMethod, "/")
			last := parts[len(parts)-1]
			structureName = goPublicIdentifier(last) + "RegistrationOptions"
		}

		// Only reference types can be embedded via extends in synthesized options.
		refTypes := []*Type{}
		for _, item := range regOptType.Items {
			if item.Kind == kindReference {
				refTypes = append(refTypes, item)
			}
		}

		// Synthesize a structure that embeds the referenced options via extends.
		syntheticStructures = append(syntheticStructures, Structure{
			Name:          structureName,
			Properties:    nil,
			Extends:       refTypes,
			Documentation: fmt.Sprintf("Registration options for %s.", ownerMethod),
		})

		// Replace the original "and" node with a named reference for stable output.
		registrationOptionTypes[i] = &Type{
			Kind: kindReference,
			Name: structureName,
		}
	}

	// Track custom "Data" placeholders for LSPAny fields that need concrete types.
	// OrderedMap preserves deterministic type emission order.
	neededDataStructures := NewOrderedMap[struct{}]()
	for si := range model.Structures {
		structure := &model.Structures[si]
		for pi := range structure.Properties {
			prop := &structure.Properties[pi]

			// Replace LSPAny initialization options with our explicit structure.
			if prop.Name == "initializationOptions" && prop.Type != nil && prop.Type.Kind == kindReference && prop.Type.Name == "LSPAny" {
				prop.Type = &Type{
					Kind: kindReference,
					Name: "InitializationOptions",
				}
			}

			// Materialize custom data containers for "data" fields.
			if prop.Name == "data" && prop.Type != nil && prop.Type.Kind == kindReference && prop.Type.Name == "LSPAny" {
				customDataType := structure.Name + "Data"
				prop.Type = &Type{
					Kind: kindReference,
					Name: customDataType,
				}
				if _, ok := explicitDataStructures()[customDataType]; !ok {
					neededDataStructures.Set(customDataType, struct{}{})
				}
			}

			// Replace registerOptions LSPAny with a union type if available.
			if prop.Name == "registerOptions" && prop.Type != nil && prop.Type.Kind == kindReference && prop.Type.Name == "LSPAny" {
				if len(registrationOptionTypes) > 0 {
					// Replace ad-hoc LSPAny with a normalized union of known registration options.
					registerOptionsUnionType = &Type{
						Kind:  kindOr,
						Items: registrationOptionTypes,
					}
					prop.Type = registerOptionsUnionType
				}
			}
		}
	}

	// Materialize any placeholder types after scanning all structures.
	for dataTypeName := range slices.Values(neededDataStructures.Keys()) {
		baseName := strings.TrimSuffix(dataTypeName, "Data")
		customStructures = append(customStructures, Structure{
			Name:          dataTypeName,
			Properties:    nil,
			Documentation: fmt.Sprintf("%s is a placeholder for custom data preserved on a %s.", dataTypeName, baseName),
		})
	}

	model.Structures = append(model.Structures, customStructures...)
	model.Structures = append(model.Structures, syntheticStructures...)

	structureMap := make(map[string]*Structure, len(model.Structures))
	for i := range model.Structures {
		structureMap[model.Structures[i].Name] = &model.Structures[i]
	}

	// Flatten extends/mixins into concrete property sets for Go struct emission.
	var collectInheritedProperties func(structure *Structure, visited map[string]struct{}) []Property
	collectInheritedProperties = func(structure *Structure, visited map[string]struct{}) []Property {
		if structure == nil {
			return nil
		}
		if visited == nil {
			visited = make(map[string]struct{})
		}
		// Guard against cycles in extends/mixins graphs.
		if _, ok := visited[structure.Name]; ok {
			return nil
		}
		visited[structure.Name] = struct{}{}

		var properties []Property
		// Merge extends and mixins for property flattening.
		inheritance := append([]*Type{}, structure.Extends...)
		inheritance = append(inheritance, structure.Mixins...)

		for t := range slices.Values(inheritance) {
			if t == nil || t.Kind != kindReference {
				continue
			}
			inheritedStructure := structureMap[t.Name]
			if inheritedStructure != nil {
				// Copy visited per branch to avoid cross-branch contamination in deep graphs.
				nextVisited := make(map[string]struct{}, len(visited))
				maps.Copy(nextVisited, visited)
				properties = append(properties, collectInheritedProperties(inheritedStructure, nextVisited)...)
				properties = append(properties, inheritedStructure.Properties...)
			}
		}

		return properties
	}

	for si := range model.Structures {
		structure := &model.Structures[si]
		inheritedProperties := collectInheritedProperties(structure, nil)

		propertyMap := NewOrderedMap[Property]()
		// Inherited properties appear first but are overwritten by local properties.
		for prop := range slices.Values(inheritedProperties) {
			propertyMap.Set(prop.Name, prop)
		}
		for prop := range slices.Values(structure.Properties) {
			propertyMap.Set(prop.Name, prop)
		}

		merged := make([]Property, 0, len(propertyMap.keys))
		for name := range slices.Values(propertyMap.keys) {
			merged = append(merged, propertyMap.values[name])
		}
		structure.Properties = merged
		// Clear inheritance after flattening to avoid embedding and duplication.
		structure.Extends = nil
		structure.Mixins = nil

		if structure.Name == "ServerCapabilities" || structure.Name == "ClientCapabilities" {
			filtered := structure.Properties[:0]
			for prop := range slices.Values(structure.Properties) {
				if prop.Name == "experimental" {
					// Drop experimental fields to keep generated structs stable.
					continue
				}
				filtered = append(filtered, prop)
			}
			structure.Properties = filtered
		}
	}

	// Drop the internal _InitializeParams placeholder to keep output clean.
	filtered := model.Structures[:0]
	for s := range slices.Values(model.Structures) {
		if s.Name == "_InitializeParams" {
			continue
		}
		filtered = append(filtered, s)
	}
	model.Structures = filtered

	return nil
}

// GoType describes the resolved Go representation of a schema type.
type GoType struct {
	Name         string
	NeedsPointer bool
}

// UnionMember captures a member of a generated union type.
type UnionMember struct {
	Name          string
	Type          *Type
	ContainedNull bool
}

// TypeInfo holds resolved type metadata during generation.
type TypeInfo struct {
	Types        map[string]GoType
	LiteralTypes *OrderedMap[string]
	UnionTypes   *OrderedMap[[]UnionMember]
	TypeAliasMap map[string]*Type
}

// newTypeInfo initializes an empty TypeInfo.
func newTypeInfo() TypeInfo {
	return TypeInfo{
		Types:        map[string]GoType{},
		LiteralTypes: NewOrderedMap[string](),
		UnionTypes:   NewOrderedMap[[]UnionMember](),
		TypeAliasMap: map[string]*Type{},
	}
}

var typeInfo TypeInfo

// titleCase returns s with its first ASCII byte uppercased.
func titleCase(s string) string {
	if s == "" {
		return ""
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// commonInitialisms is based on the set used by golint and the Google Go Style Guide.
// It is used to produce idiomatic Go identifiers from schema / JSON names.
var commonInitialisms = map[string]struct{}{
	"API":   {},
	"ASCII": {},
	"CPU":   {},
	"CSS":   {},
	"DNS":   {},
	"EOF":   {},
	"GUID":  {},
	"HTML":  {},
	"HTTP":  {},
	"HTTPS": {},
	"ID":    {},
	"IP":    {},
	"JSON":  {},
	"LHS":   {},
	"QPS":   {},
	"RAM":   {},
	"RHS":   {},
	"RPC":   {},
	"SLA":   {},
	"SMTP":  {},
	"SQL":   {},
	"SSH":   {},
	"TCP":   {},
	"TLS":   {},
	"TTL":   {},
	"UDP":   {},
	"UI":    {},
	"UID":   {},
	"UUID":  {},
	"URI":   {},
	"URL":   {},
	"UTF8":  {},
	"VM":    {},
	"XML":   {},
	"XMPP":  {},
	"XSRF":  {},
	"XSS":   {},
	"LSP":   {},
}

// goPublicIdentifier converts a schema identifier to a Go-exported name.
func goPublicIdentifier(name string) string {
	if name == "" {
		return ""
	}

	words := splitIdentifierWords(name)
	if len(words) == 0 {
		return ""
	}

	var b strings.Builder
	for word := range slices.Values(words) {
		if word == "" {
			continue
		}

		upper := strings.ToUpper(word)
		if _, ok := commonInitialisms[upper]; ok {
			b.WriteString(upper)
			continue
		}

		// Handle plural initialisms: "Ids" -> "IDs", "Uris" -> "URIs".
		if strings.HasSuffix(word, "s") && len(word) > 1 {
			base := word[:len(word)-1]
			baseUpper := strings.ToUpper(base)
			if _, ok := commonInitialisms[baseUpper]; ok {
				b.WriteString(baseUpper)
				b.WriteByte('s')
				continue
			}
			// Preserve pluralized acronyms not in the initialism list: "ABAPs" -> "ABAPs".
			if baseUpper == base && len(base) > 1 {
				b.WriteString(base)
				b.WriteByte('s')
				continue
			}
		}

		// Preserve already-uppercase words (e.g. ABAP, CPP) that aren't in the
		// initialism list.
		if upper == word {
			b.WriteString(word)
			continue
		}

		lower := strings.ToLower(word)
		b.WriteString(strings.ToUpper(lower[:1]))
		b.WriteString(lower[1:])
	}

	out := b.String()
	if out == "" {
		return ""
	}

	// Avoid invalid identifiers if we ever encounter a name starting with a digit.
	if isDigit(out[0]) {
		return "X" + out
	}

	return out
}

// splitIdentifierWords splits an identifier into word-like chunks.
func splitIdentifierWords(s string) []string {
	if s == "" {
		return nil
	}

	var words []string
	start := 0

	flush := func(i int) {
		if start < i {
			words = append(words, s[start:i])
		}
	}

	// Split on non-alnum boundaries and on case/digit transitions within words.
	for i := range len(s) {
		ch := s[i]
		if !isAlphaNum(ch) {
			flush(i)
			start = i + 1
			continue
		}
		if i == start {
			continue
		}

		prev := s[i-1]
		if !isAlphaNum(prev) {
			continue
		}

		if isUpper(ch) && isDigit(prev) {
			flush(i)
			start = i
			continue
		}
		if isUpper(ch) && isLower(prev) {
			flush(i)
			start = i
			continue
		}
		if isUpper(ch) && isUpper(prev) && i+1 < len(s) && isLower(s[i+1]) {
			// Split "JSONText" into ["JSON", "Text"].
			flush(i)
			start = i
			continue
		}
	}

	flush(len(s))

	return words
}

// isUpper reports whether b is an ASCII uppercase letter.
func isUpper(b byte) bool { return b >= 'A' && b <= 'Z' }

// isLower reports whether b is an ASCII lowercase letter.
func isLower(b byte) bool { return b >= 'a' && b <= 'z' }

// isLetter reports whether b is an ASCII letter.
func isLetter(b byte) bool { return isUpper(b) || isLower(b) }

// isDigit reports whether b is an ASCII digit.
func isDigit(b byte) bool { return b >= '0' && b <= '9' }

// isAlphaNum reports whether b is an ASCII letter or digit.
func isAlphaNum(b byte) bool { return isLetter(b) || isDigit(b) }

// resolveType converts a schema Type into its GoType representation.
func resolveType(t *Type) GoType {
	switch t.Kind {
	case kindBase:
		switch t.Name {
		case "integer":
			return GoType{
				Name:         "int32",
				NeedsPointer: false,
			}

		case "uinteger":
			return GoType{
				Name:         "uint32",
				NeedsPointer: false,
			}

		case "string":
			return GoType{
				Name:         "string",
				NeedsPointer: false,
			}

		case "boolean":
			return GoType{
				Name:         "bool",
				NeedsPointer: false,
			}

		case "URI":
			return GoType{
				Name:         "*uri.URI",
				NeedsPointer: false,
			}

		case "DocumentUri":
			return GoType{
				Name:         "*uri.URI",
				NeedsPointer: false,
			}

		case "decimal":
			return GoType{
				Name:         "float64",
				NeedsPointer: false,
			}

		case "null":
			return GoType{
				Name:         "any",
				NeedsPointer: false,
			}

		default:
			panic(fmt.Sprintf("Unsupported base type: %s", t.Name))
		}

	case kindReference:
		// Resolve aliases/overrides first; unknown references are recorded for later output.
		if override, ok := typeAliasOverrides[t.Name]; ok {
			return override
		}
		if aliased, ok := typeInfo.TypeAliasMap[t.Name]; ok {
			return resolveType(aliased)
		}
		if refType, ok := typeInfo.Types[t.Name]; ok {
			return refType
		}
		refType := GoType{
			Name:         goPublicIdentifier(t.Name),
			NeedsPointer: true,
		}
		typeInfo.Types[t.Name] = refType

		return refType

	case kindArray:
		// Arrays themselves are values; element pointer-ness is encoded in the element type.
		elem := resolveType(t.Element)
		name := "[]" + elem.Name
		if elem.NeedsPointer {
			name = "[]*" + elem.Name
		}

		return GoType{
			Name:         name,
			NeedsPointer: false,
		}

	case kindMap:
		// Map values preserve pointer-ness to keep optional/nullable semantics.
		key := resolveType(t.Key)
		val := resolveType(t.Value)
		valName := val.Name
		if val.NeedsPointer {
			valName = "*" + valName
		}

		return GoType{
			Name:         fmt.Sprintf("map[%s]%s", key.Name, valName),
			NeedsPointer: false,
		}

	case kindTuple:
		// The only supported tuple is [uinteger, uinteger], which maps to a fixed array.
		if len(t.Items) == 2 && t.Items[0].Kind == kindBase && t.Items[0].Name == "uinteger" && t.Items[1].Kind == kindBase && t.Items[1].Name == "uinteger" {
			return GoType{
				Name:         "[2]uint32",
				NeedsPointer: false,
			}
		}
		panic(fmt.Sprintf("Unsupported tuple type: %v", t))

	case kindStringLiteral:
		typeName := "StringLiteral" + titleCase(*t.StringValue)
		typeInfo.LiteralTypes.Set(fmt.Sprintf("%v", *t.StringValue), typeName)

		return GoType{
			Name:         typeName,
			NeedsPointer: false,
		}

	case kindIntegerLiteral:
		typeName := fmt.Sprintf("IntegerLiteral%d", *t.IntegerValue)
		typeInfo.LiteralTypes.Set(fmt.Sprintf("%v", *t.IntegerValue), typeName)

		return GoType{
			Name:         typeName,
			NeedsPointer: false,
		}

	case kindBooleanLiteral:
		typeName := "BooleanLiteral"
		if *t.BoolValue {
			typeName += "True"
		} else {
			typeName += "False"
		}
		typeInfo.LiteralTypes.Set(fmt.Sprintf("%v", *t.BoolValue), typeName)

		return GoType{
			Name:         typeName,
			NeedsPointer: false,
		}

	case kindLiteral:
		// Only empty object literals are supported; others are schema errors.
		if t.Literal != nil && len(t.Literal.Properties) == 0 {
			return GoType{
				Name:         "struct{}",
				NeedsPointer: false,
			}
		}
		panic(fmt.Sprintf("Unexpected non-empty literal object: %v", t.Literal))

	case kindOr:
		// Unions become wrapper types with custom (un)marshal logic.
		return handleOrType(t)

	default:
		panic(fmt.Sprintf("Unsupported type kind: %s", t.Kind))
	}
}

// flattenOrTypes expands nested union types and removes duplicates.
func flattenOrTypes(types []*Type) []*Type {
	flattened := []*Type{}
	// seen tracks raw node pointers so we dedupe while preserving first-seen order.
	seen := make(map[*Type]struct{})

	add := func(raw *Type) {
		if raw == nil {
			return
		}

		t := raw
		if raw.Kind == kindReference {
			// Inline union aliases so nested "or" types don't become nested wrappers.
			if aliased, ok := typeInfo.TypeAliasMap[raw.Name]; ok && aliased.Kind == kindOr {
				t = aliased
			}
		}

		if t.Kind == kindOr {
			// Recursively inline nested unions but keep the outer ordering stable.
			for sub := range slices.Values(flattenOrTypes(t.Items)) {
				if _, ok := seen[sub]; !ok {
					seen[sub] = struct{}{}
					flattened = append(flattened, sub)
				}
			}
			return
		}

		if _, ok := seen[raw]; !ok {
			seen[raw] = struct{}{}
			flattened = append(flattened, raw)
		}
	}

	for t := range slices.Values(types) {
		add(t)
	}

	return flattened
}

// pluralize applies minimal English pluralization for identifier parts.
func pluralize(name string) string {
	if strings.HasSuffix(name, "s") || strings.HasSuffix(name, "x") || strings.HasSuffix(name, "z") || strings.HasSuffix(name, "ch") || strings.HasSuffix(name, "sh") {
		return name + "es"
	}

	if strings.HasSuffix(name, "y") && len(name) > 1 {
		penultimate := name[len(name)-2 : len(name)-1]
		if !strings.ContainsAny(penultimate, "aeiou") {
			return name[:len(name)-1] + "ies"
		}
	}

	return name + "s"
}

// handleOrType resolves a union type into a generated Go union wrapper.
func handleOrType(orType *Type) GoType {
	// Flatten nested unions first so naming and member ordering are deterministic.
	types := flattenOrTypes(orType.Items)

	// Extract a single null branch to drive optional union handling.
	nullIndex := -1
	for i, t := range types {
		if t.Kind == kindBase && t.Name == "null" {
			nullIndex = i
			break
		}
	}
	containedNull := nullIndex != -1

	nonNullTypes := types
	if containedNull {
		// Preserve ordering while removing the single null branch.
		nonNullTypes = append([]*Type{}, types[:nullIndex]...)
		nonNullTypes = append(nonNullTypes, types[nullIndex+1:]...)
	}
	if len(nonNullTypes) == 0 {
		panic(fmt.Sprintf("Union type with only null is not supported: %v", types))
	}

	// Derive member field names from type shapes to keep union fields meaningful.
	memberNames := make([]string, len(nonNullTypes))
	for i, t := range nonNullTypes {
		switch t.Kind {
		case kindReference:
			memberNames[i] = goPublicIdentifier(t.Name)

		case kindBase:
			memberNames[i] = goPublicIdentifier(t.Name)

		case kindArray:
			if t.Element.Kind == kindReference || t.Element.Kind == kindBase {
				memberNames[i] = pluralize(goPublicIdentifier(t.Element.Name))
			} else {
				elem := resolveType(t.Element)
				memberNames[i] = elem.Name + "Array"
			}

		case kindLiteral:
			if t.Literal != nil && len(t.Literal.Properties) == 0 {
				memberNames[i] = "EmptyObject"
			} else {
				panic(fmt.Sprintf("Unsupported type kind in union: %s", t.Kind))
			}

		case kindTuple:
			memberNames[i] = "Tuple"

		default:
			panic(fmt.Sprintf("Unsupported type kind in union: %s", t.Kind))
		}
	}

	findLongestCommonPrefix := func(names []string) string {
		if len(names) <= 1 {
			return ""
		}

		splitPascalCase := func(name string) []string {
			var chunks []string
			current := ""
			for i := range len(name) {
				ch := name[i]
				// Start a new chunk when we hit an uppercase boundary.
				if isUpper(ch) && current != "" {
					chunks = append(chunks, current)
					current = string(ch)
				} else {
					current += string(ch)
				}
			}
			if current != "" {
				chunks = append(chunks, current)
			}
			return chunks
		}

		allChunks := make([][]string, len(names))
		minLen := -1
		for i, n := range names {
			chunks := splitPascalCase(n)
			allChunks[i] = chunks
			if minLen == -1 || len(chunks) < minLen {
				minLen = len(chunks)
			}
		}

		var common []string
		for i := range minLen {
			chunk := allChunks[0][i]
			allMatch := true
			for c := range slices.Values(allChunks[1:]) {
				if c[i] != chunk {
					allMatch = false
					break
				}
			}
			if !allMatch {
				break
			}
			common = append(common, chunk)
		}

		return strings.Join(common, "")
	}

	// Prefer a shared prefix to keep union type names compact.
	commonPrefix := findLongestCommonPrefix(memberNames)
	unionTypeName := ""

	if commonPrefix != "" {
		trimmed := make([]string, len(memberNames))
		allNonEmpty := true
		for i, name := range memberNames {
			trimmed[i] = strings.TrimPrefix(name, commonPrefix)
			if trimmed[i] == "" {
				allNonEmpty = false
			}
		}
		if allNonEmpty {
			unionTypeName = commonPrefix + strings.Join(trimmed, "Or")
			memberNames = trimmed
		} else {
			unionTypeName = strings.Join(memberNames, "Or")
		}
	} else {
		unionTypeName = strings.Join(memberNames, "Or")
	}

	// Special-case RegisterOptions unions to keep stable naming across versions.
	if orType == registerOptionsUnionType {
		// Collapse "XRegistrationOptions" members to "X" for stable union members.
		unionTypeName = "RegisterOptions"
		for i, name := range memberNames {
			if before, ok := strings.CutSuffix(name, "RegistrationOptions"); ok {
				memberNames[i] = before
			}
		}
	}

	if containedNull {
		// Only union types that explicitly included null get the OrNull suffix.
		unionTypeName += "OrNull"
	} else {
		containedNull = false
	}

	union := make([]UnionMember, len(memberNames))
	for i, name := range memberNames {
		union[i] = UnionMember{
			Name:          name,
			Type:          nonNullTypes[i],
			ContainedNull: containedNull,
		}
	}

	// Register the union for later code generation.
	typeInfo.UnionTypes.Set(unionTypeName, union)

	return GoType{
		Name:         unionTypeName,
		NeedsPointer: false,
	}
}

// typeAliasOverrides maps schema type aliases to Go types.
var typeAliasOverrides = map[string]GoType{
	"LSPAny": {
		Name:         "any",
		NeedsPointer: false,
	},
	"LSPArray": {
		Name:         "[]any",
		NeedsPointer: false,
	},
	"LSPObject": {
		Name:         "map[string]any",
		NeedsPointer: false,
	},
	"uint64": {
		Name:         "uint64",
		NeedsPointer: false,
	},
}

// collectTypeDefinitions populates typeInfo with structs, enums, and aliases.
func collectTypeDefinitions(model *MetaModel) {
	for enumeration := range slices.Values(model.Enumerations) {
		typeInfo.Types[enumeration.Name] = GoType{
			Name:         goPublicIdentifier(enumeration.Name),
			NeedsPointer: false,
		}
	}

	valueTypes := map[string]struct{}{
		"Position":                            {},
		"Range":                               {},
		"Location":                            {},
		"Color":                               {},
		"TextDocumentIdentifier":              {},
		"NotebookDocumentIdentifier":          {},
		"PreviousResultId":                    {},
		"VersionedNotebookDocumentIdentifier": {},
		"VersionedTextDocumentIdentifier":     {},
		"OptionalVersionedTextDocumentIdentifier": {},
		"ExportInfoMapKey":                        {},
	}

	for structure := range slices.Values(model.Structures) {
		_, isValue := valueTypes[structure.Name]
		typeInfo.Types[structure.Name] = GoType{
			Name:         goPublicIdentifier(structure.Name),
			NeedsPointer: !isValue,
		}
	}

	for alias := range slices.Values(model.TypeAliases) {
		if _, ok := typeAliasOverrides[alias.Name]; ok {
			continue
		}
		typeInfo.TypeAliasMap[alias.Name] = alias.Type
	}
}

var (
	spaceRE = regexp.MustCompile(`(\w ) +`)
	linkRE  = regexp.MustCompile(`\{@link(?:code)?.*?([^} ]+)\}`)
	tagRE   = regexp.MustCompile(`^@(since|proposed|deprecated)(.*)`)
)

// formatDocumentation converts schema docs into Go line comments.
func formatDocumentation(s string) string {
	if s == "" {
		return ""
	}

	var lines []string
	for line := range strings.SplitSeq(s, "\n") {
		line = strings.TrimRight(line, " \t\r")
		line = spaceRE.ReplaceAllString(line, "$1")
		line = linkRE.ReplaceAllString(line, "$1")
		if matches := tagRE.FindStringSubmatch(line); len(matches) > 0 {
			lines = append(lines, "")
			tag := titleCase(matches[1])
			rest := matches[2]
			if rest != "" {
				line = fmt.Sprintf("%s:%s", tag, rest)
			} else {
				line = fmt.Sprintf("%s.", tag)
			}
		}
		lines = append(lines, line)
	}

	for {
		removed := false
		for i := range len(lines) {
			if lines[i] != "" {
				continue
			}
			// Drop edge or duplicate blank lines to keep docs compact.
			if i == 0 || i == len(lines)-1 || !(lines[i-1] != "" && lines[i+1] != "") {
				lines = append(lines[:i], lines[i+1:]...)
				removed = true
				break
			}
		}
		if !removed {
			break
		}
	}

	if len(lines) == 0 {
		return ""
	}

	return "// " + strings.Join(lines, "\n// ") + "\n"
}

// methodNameIdentifier builds a Go identifier from a protocol method name.
func methodNameIdentifier(name string) string {
	parts := strings.Split(name, "/")
	for i, p := range parts {
		if p == "$" {
			parts[i] = ""
		} else {
			parts[i] = goPublicIdentifier(p)
		}
	}
	return strings.Join(parts, "")
}

// codeWriter is a minimal writer used for code generation.
type codeWriter struct {
	b strings.Builder
}

// Write appends raw text to the code writer.
func (w *codeWriter) Write(s string) {
	w.b.WriteString(s)
}

// WriteLine appends text followed by a newline.
func (w *codeWriter) WriteLine(s string) {
	w.b.WriteString(s)
	w.b.WriteByte('\n')
}

func generateResolvedStruct(model *MetaModel, structure *Structure, indent string) []string {
	var lines []string
	for prop := range slices.Values(structure.Properties) {
		if prop.Documentation != "" {
			propDoc := formatDocumentation(prop.Documentation)
			if propDoc != "" {
				for line := range strings.SplitSeq(strings.TrimRight(propDoc, "\n"), "\n") {
					lines = append(lines, indent+line)
				}
			}
		}

		fieldName := goPublicIdentifier(prop.Name)

		t := resolveType(prop.Type)
		if prop.Type.Kind == kindReference {
			// Use the model (TypeScript) name for lookups, but the Go name for emitted identifiers.
			if refStructure := findStructure(model.Structures, prop.Type.Name); refStructure != nil {
				lines = append(lines, fmt.Sprintf("%s%s Resolved%s `json:\"%s,omitzero\"`", indent, fieldName, t.Name, prop.Name))
				continue
			}
		}
		lines = append(lines, fmt.Sprintf("%s%s %s `json:\"%s,omitzero\"`", indent, fieldName, t.Name, prop.Name))
	}

	return lines
}

func generateResolveConversion(model *MetaModel, structure *Structure, varName, indent string) []string {
	var lines []string
	for prop := range slices.Values(structure.Properties) {
		t := resolveType(prop.Type)
		fieldName := goPublicIdentifier(prop.Name)
		access := varName + "." + fieldName
		if prop.Type.Kind == kindReference {
			if refStructure := findStructure(model.Structures, prop.Type.Name); refStructure != nil {
				lines = append(lines, fmt.Sprintf("%s%s: resolve%s(%s),", indent, fieldName, t.Name, access))
				continue
			}
		}

		if prop.Optional || t.NeedsPointer {
			lines = append(lines, fmt.Sprintf("%s%s: derefOr(%s),", indent, fieldName, access))
		} else {
			lines = append(lines, fmt.Sprintf("%s%s: %s,", indent, fieldName, access))
		}
	}

	return lines
}

func collectStructureDependencies(model *MetaModel, structure *Structure, visited map[string]struct{}) []*Structure {
	if structure == nil {
		return nil
	}
	if visited == nil {
		visited = make(map[string]struct{})
	}
	if _, ok := visited[structure.Name]; ok {
		return nil
	}
	visited[structure.Name] = struct{}{}

	var deps []*Structure
	for prop := range slices.Values(structure.Properties) {
		if prop.Type.Kind == kindReference {
			ref := findStructure(model.Structures, prop.Type.Name)
			if ref != nil {
				nextVisited := make(map[string]struct{}, len(visited))
				maps.Copy(nextVisited, visited)
				deps = append(deps, collectStructureDependencies(model, ref, nextVisited)...)
				deps = append(deps, ref)
			}
		}
	}
	return deps
}

func generateResolvedTypeAndHelper(model *MetaModel, structure *Structure, isMain bool) []string {
	var lines []string
	goStructureName := goPublicIdentifier(structure.Name)
	typeName := "Resolved" + goStructureName
	funcName := "resolve" + goStructureName
	if isMain {
		funcName = "Resolve" + goStructureName
	}

	if !isMain {
		if structure.Documentation != "" {
			typeDoc := formatDocumentation(structure.Documentation)
			lines = append(lines, fmt.Sprintf("// %s is a resolved version of %s with all optional fields", typeName, goStructureName))
			lines = append(lines, "// converted to non-pointer values for easier access.")
			lines = append(lines, "//")
			if typeDoc != "" {
				lines = append(lines, strings.TrimRight(typeDoc, "\n"))
			}
		} else {
			lines = append(lines, fmt.Sprintf("// %s is a resolved version of %s with all optional fields", typeName, goStructureName))
			lines = append(lines, "// converted to non-pointer values for easier access.")
		}
	}

	lines = append(lines, fmt.Sprintf("type %s struct {", typeName))
	lines = append(lines, generateResolvedStruct(model, structure, "\t")...)
	lines = append(lines, "}")
	lines = append(lines, "")

	lines = append(lines, fmt.Sprintf("func %s(v *%s) %s {", funcName, goStructureName, typeName))
	lines = append(lines, "\tif v == nil {")
	lines = append(lines, fmt.Sprintf("\t\treturn %s{}", typeName))
	lines = append(lines, "\t}")
	lines = append(lines, fmt.Sprintf("\treturn %s{", typeName))
	lines = append(lines, generateResolveConversion(model, structure, "v", "\t\t")...)
	lines = append(lines, "\t}")
	lines = append(lines, "}")
	lines = append(lines, "")
	return lines
}

func generateStructFields(w *codeWriter, structure *Structure, name string, includeDocumentation bool) {
	write := w.Write
	writeLine := w.WriteLine

	if includeDocumentation {
		write(formatDocumentation(structure.Documentation))
	}
	writeLine("type " + name + " struct {")
	for prop := range slices.Values(structure.Properties) {
		if includeDocumentation {
			write(formatDocumentation(prop.Documentation))
		}
		t := resolveType(prop.Type)
		useOmitzero := prop.Optional || prop.OmitzeroValue
		goType := t.Name
		if (prop.Optional || t.NeedsPointer) && !prop.OmitzeroValue {
			goType = "*" + goType
		}
		tag := prop.Name
		if useOmitzero {
			tag += ",omitzero"
		}
		writeLine(fmt.Sprintf("\t%s %s `json:\"%s\"`", goPublicIdentifier(prop.Name), goType, tag))
		if includeDocumentation {
			writeLine("")
		}
	}
	writeLine("}")
	writeLine("")
}

// generateCode emits Go source for the provided meta model.
func generateCode(model *MetaModel) string {
	w := &codeWriter{}

	write := w.Write
	writeLine := w.WriteLine

	writeLine(generatedHeader)
	writeLine("")
	writeLine("// Code generated by lspgen.go; DO NOT EDIT.")
	writeLine("")
	writeLine("package protocol")
	writeLine("")
	writeLine("import (")
	writeLine("\t\"fmt\"")
	writeLine("\t\"strings\"")
	writeLine("")
	writeLine("\t\"github.com/go-json-experiment/json\"")
	writeLine("\t\"github.com/go-json-experiment/json/jsontext\"")
	writeLine("")
	writeLine("\t\"go.lsp.dev/uri\"")
	writeLine(")")
	writeLine("")
	writeLine("// Meta model version " + model.MetaData.Version)
	writeLine("")
	writeLine("// Structures")
	writeLine("")

	for si := range model.Structures {
		structure := &model.Structures[si]
		goStructureName := goPublicIdentifier(structure.Name)
		generateStructFields(w, structure, goStructureName, true)
		writeLine("")

		if hasTextDocumentURI(structure) {
			writeLine(fmt.Sprintf("func (s *%s) TextDocumentURI() *uri.URI {", goStructureName))
			writeLine("\treturn s.TextDocument.URI")
			writeLine("}")
			writeLine("")

			if hasTextDocumentPosition(structure) {
				writeLine(fmt.Sprintf("func (s *%s) TextDocumentPosition() Position {", goStructureName))
				writeLine("\treturn s.Position")
				writeLine("}")
				writeLine("")
			}
		}

		// Generate a custom unmarshaler when required fields need enforcement.
		requiredProps := make([]Property, 0, len(structure.Properties))
		for p := range slices.Values(structure.Properties) {
			if p.Optional || p.OmitzeroValue {
				continue
			}
			requiredProps = append(requiredProps, p)
		}

		if len(requiredProps) > 0 {
			writeLine(fmt.Sprintf("\tvar _ json.UnmarshalerFrom = (*%s)(nil)", goStructureName))
			writeLine("")
			writeLine(fmt.Sprintf("func (s *%s) UnmarshalJSONFrom(dec *jsontext.Decoder) error {", goStructureName))
			writeLine("\tconst (")
			for i, prop := range requiredProps {
				iotaPrefix := ""
				if i == 0 {
					iotaPrefix = " uint = 1 << iota"
				}
				writeLine(fmt.Sprintf("\t\tmissing%s%s", goPublicIdentifier(prop.Name), iotaPrefix))
			}
			writeLine("\t\tmissingLast")
			writeLine("\t)")
			writeLine("\tmissing := missingLast - 1")
			writeLine("")
			writeLine("\tif k := dec.PeekKind(); k != '{' {")
			writeLine("\t\treturn fmt.Errorf(\"expected object start, but encountered %v\", k)")
			writeLine("\t}")
			writeLine("\tif _, err := dec.ReadToken(); err != nil {")
			writeLine("\t\treturn err")
			writeLine("\t}")
			writeLine("")
			writeLine("\tfor dec.PeekKind() != '}' {")
			writeLine("\tname, err := dec.ReadValue()")
			writeLine("\t\tif err != nil {")
			writeLine("\t\t\treturn err")
			writeLine("\t\t}")
			writeLine("\t\tswitch string(name) {")
			for prop := range slices.Values(structure.Properties) {
				writeLine(fmt.Sprintf("\t\tcase `\"%s\"`:", prop.Name))
				if !prop.Optional && !prop.OmitzeroValue {
					writeLine(fmt.Sprintf("\t\t\tmissing &^= missing%s", goPublicIdentifier(prop.Name)))
				}
				writeLine(fmt.Sprintf("\t\t\tif err := json.UnmarshalDecode(dec, &s.%s); err != nil {", goPublicIdentifier(prop.Name)))
				writeLine("\t\t\t\treturn err")
				writeLine("\t\t\t}")
			}
			writeLine("\t\tdefault:")
			writeLine("\t\t// Ignore unknown properties.")
			writeLine("\t\t}")
			writeLine("\t}")
			writeLine("")
			writeLine("\tif _, err := dec.ReadToken(); err != nil {")
			writeLine("\t\treturn err")
			writeLine("\t}")
			writeLine("")
			writeLine("\tif missing != 0 {")
			writeLine("\t\tvar missingProps []string")
			for prop := range slices.Values(requiredProps) {
				writeLine(fmt.Sprintf("\t\tif missing&missing%s != 0 {", goPublicIdentifier(prop.Name)))
				writeLine(fmt.Sprintf("\t\t\tmissingProps = append(missingProps, \"%s\")", prop.Name))
				writeLine("\t\t}")
			}
			writeLine("\t\treturn fmt.Errorf(\"missing required properties: %s\", strings.Join(missingProps, \", \") )")
			writeLine("\t}")
			writeLine("")
			writeLine("\treturn nil")
			writeLine("}")
			writeLine("")
		}
	}

	// Enumerations marked here need bitflag-style stringification.
	bitflagEnums := map[string]struct{}{
		"WatchKind": {},
	}
	isBitflagEnum := func(enum Enumeration) bool {
		_, ok := bitflagEnums[enum.Name]
		return ok
	}

	writeLine("// Enumerations")
	writeLine("")

	for enumeration := range slices.Values(model.Enumerations) {
		write(formatDocumentation(enumeration.Documentation))
		goEnumName := goPublicIdentifier(enumeration.Name)
		var baseType string
		switch enumeration.Type.Name {
		case "string":
			baseType = "string"
		case "integer":
			baseType = "int32"
		case "uinteger":
			baseType = "uint32"
		default:
			panic(fmt.Sprintf("Unsupported enum type: %s", enumeration.Type.Name))
		}
		writeLine(fmt.Sprintf("type %s %s", goEnumName, baseType))
		writeLine("")

		enumValues := make([]NumericValue, len(enumeration.Values))
		for i, value := range enumeration.Values {
			asNumber, _ := toNumber(value.ValueRaw)
			goValueName := goPublicIdentifier(value.Name)
			enumValues[i] = NumericValue{
				Value:         fmt.Sprint(value.ValueRaw),
				NumericValue:  asNumber,
				Name:          goValueName,
				Identifier:    goEnumName + goValueName,
				Documentation: value.Documentation,
			}
		}

		writeLine("const (")
		for entry := range slices.Values(enumValues) {
			write(formatDocumentation(entry.Documentation))
			valueLiteral := entry.Value
			if enumeration.Type.Name == "string" {
				valueLiteral = strings.TrimSuffix(strings.TrimPrefix(entry.Value, "\""), "\"")
				valueLiteral = fmt.Sprintf("\"%s\"", valueLiteral)
			}
			writeLine(fmt.Sprintf("\t%s %s = %s", entry.Identifier, goEnumName, valueLiteral))
		}
		writeLine(")")

		writeLine("")

		if enumeration.Type.Name != "string" {
			if isBitflagEnum(enumeration) {
				// Precompute name/index tables so String can slice without allocations.
				sorted := append([]NumericValue{}, enumValues...)
				sortByNumericValue(sorted)
				names := make([]string, len(sorted))
				values := make([]float64, len(sorted))
				for i, v := range sorted {
					names[i] = v.Name
					values[i] = v.NumericValue
				}
				nameConst := "_" + goEnumName + "_name"
				indexVar := "_" + goEnumName + "_index"
				combinedNames := strings.Join(names, "")
				writeLine(fmt.Sprintf("const %s = \"%s\"", nameConst, combinedNames))
				write("var " + indexVar + " = [...]uint16{0")
				offset := 0
				for name := range slices.Values(names) {
					offset += len(name)
					write(fmt.Sprintf(", %d", offset))
				}
				writeLine("}")
				writeLine("")

				writeLine(fmt.Sprintf("func (e %s) String() string {", goEnumName))
				writeLine("\tif e == 0 {")
				writeLine("\t\treturn \"0\"")
				writeLine("\t}")
				writeLine("\tvar parts []string")
				for i, val := range values {
					writeLine(fmt.Sprintf("\tif e&%v != 0 {", val))
					writeLine(fmt.Sprintf("\t\tparts = append(parts, %s[%s[%d]:%s[%d+1]])", nameConst, indexVar, i, indexVar, i))
					writeLine("\t}")
				}
				writeLine("\tif len(parts) == 0 {")
				writeLine(fmt.Sprintf("\t\treturn fmt.Sprintf(\"%s(%%d)\", e)", goEnumName))
				writeLine("\t}")
				writeLine("\treturn strings.Join(parts, \"|\")")
				writeLine("}")
				writeLine("")
			} else {
				sortByNumericValue(enumValues)

				runs := splitNumeric(enumValues)
				nameConst := "_" + goEnumName + "_name"
				indexVar := "_" + goEnumName + "_index"

				// Choose the most compact String() encoding based on numeric sparsity.
				switch {
				case len(runs) == 1:
					combined := strings.Builder{}
					for n := range slices.Values(runs[0].Names) {
						combined.WriteString(n)
					}
					writeLine(fmt.Sprintf("const %s = \"%s\"", nameConst, combined.String()))
					write("var " + indexVar + " = [...]uint16{0")
					offset := 0
					for n := range slices.Values(runs[0].Names) {
						offset += len(n)
						write(fmt.Sprintf(", %d", offset))
					}
					writeLine("}")
					writeLine("")
					minVal := runs[0].Values[0]
					writeLine(fmt.Sprintf("func (e %s) String() string {", goEnumName))
					writeLine(fmt.Sprintf("\ti := int(e) - %d", int(minVal)))
					writeLine(fmt.Sprintf("\tif i < 0 || i >= len(%s)-1 {", indexVar))
					writeLine(fmt.Sprintf("\t\treturn fmt.Sprintf(\"%s(%%d)\", e)", goEnumName))
					writeLine("\t}")
					writeLine(fmt.Sprintf("\treturn %s[%s[i]:%s[i+1]]", nameConst, indexVar, indexVar))
					writeLine("}")
					writeLine("")

				case len(runs) <= 10:
					var allNames strings.Builder
					type runinfo struct {
						StartOffset int
						EndOffset   int
						MinVal      int
						MaxVal      int
					}
					runInfo := make([]runinfo, len(runs))
					offset := 0
					for i, run := range runs {
						runInfo[i].StartOffset = offset
						for n := range slices.Values(run.Names) {
							offset += len(n)
							allNames.WriteString(n)
						}
						runInfo[i].EndOffset = offset
						runInfo[i].MinVal = int(run.Values[0])
						runInfo[i].MaxVal = int(run.Values[len(run.Values)-1])
					}
					writeLine(fmt.Sprintf("const %s = \"%s\"", nameConst, allNames.String()))
					writeLine("")
					for i, run := range runs {
						idx := fmt.Sprintf("%s_%d", indexVar, i)
						write("var " + idx + " = [...]uint16{0")
						offset := 0
						for n := range slices.Values(run.Names) {
							offset += len(n)
							write(fmt.Sprintf(", %d", offset))
						}
						writeLine("}")
					}
					writeLine("")

					writeLine(fmt.Sprintf("func (e %s) String() string {", goEnumName))
					writeLine("\tswitch {")
					for i, run := range runs {
						info := runInfo[i]
						idx := fmt.Sprintf("%s_%d", indexVar, i)
						if len(run.Values) == 1 {
							writeLine(fmt.Sprintf("\tcase e == %d:", int(run.Values[0])))
							writeLine(fmt.Sprintf("\t\treturn %s[%d:%d]", nameConst, info.StartOffset, info.EndOffset))
						} else {
							if info.MinVal == 0 && strings.HasPrefix(baseType, "uint") {
								writeLine(fmt.Sprintf("\tcase e <= %d:", info.MaxVal))
							} else if info.MinVal == 0 {
								writeLine(fmt.Sprintf("\tcase 0 <= e && e <= %d:", info.MaxVal))
							} else {
								writeLine(fmt.Sprintf("\tcase %d <= e && e <= %d:", info.MinVal, info.MaxVal))
							}
							writeLine(fmt.Sprintf("\t\ti := int(e) - %d", info.MinVal))
							writeLine(fmt.Sprintf("\t\treturn %s[%d+%s[i]:%d+%s[i+1]]", nameConst, info.StartOffset, idx, info.StartOffset, idx))
						}
					}
					writeLine("\tdefault:")
					writeLine(fmt.Sprintf("\t\treturn fmt.Sprintf(\"%s(%%d)\", e)", goEnumName))
					writeLine("\t}")
					writeLine("}")
					writeLine("")

				default:
					var allNames strings.Builder
					type valueMapEntry struct {
						Value       int
						StartOffset int
						EndOffset   int
					}
					var valueMap []valueMapEntry
					offset := 0
					for run := range slices.Values(runs) {
						for i, name := range run.Names {
							start := offset
							offset += len(name)
							valueMap = append(valueMap, valueMapEntry{
								Value:       int(run.Values[i]),
								StartOffset: start,
								EndOffset:   offset,
							})
							allNames.WriteString(name)
						}
					}
					writeLine(fmt.Sprintf("const %s = \"%s\"", nameConst, allNames.String()))
					writeLine("")
					writeLine(fmt.Sprintf("var %s_map = map[%s]string{", goEnumName, goEnumName))
					for entry := range slices.Values(valueMap) {
						writeLine(fmt.Sprintf("\t%d: %s[%d:%d],", entry.Value, nameConst, entry.StartOffset, entry.EndOffset))
					}
					writeLine("}")
					writeLine("")
					writeLine(fmt.Sprintf("func (e %s) String() string {", goEnumName))
					writeLine(fmt.Sprintf("\tif str, ok := %s_map[e]; ok {", goEnumName))
					writeLine("\t\treturn str")
					writeLine("\t}")
					writeLine(fmt.Sprintf("\treturn fmt.Sprintf(\"%s(%%d)\", e)", goEnumName))
					writeLine("}")
					writeLine("")
				}
			}
		}
	}

	// Treat requests and notifications uniformly for method tables.
	requestsAndNotifications := append([]Request{}, model.Requests...)
	for n := range slices.Values(model.Notifications) {
		requestsAndNotifications = append(requestsAndNotifications, Request{
			Method:              n.Method,
			TypeName:            n.TypeName,
			Params:              n.Params,
			ParamsArray:         n.ParamsArray,
			RegistrationMethod:  n.RegistrationMethod,
			RegistrationOptions: n.RegistrationOptions,
			MessageDirection:    n.MessageDirection,
			Documentation:       n.Documentation,
			Since:               n.Since,
			SinceTags:           n.SinceTags,
			Proposed:            n.Proposed,
			Deprecated:          n.Deprecated,
		})
	}

	writeLine("func unmarshalParams(method Method, data []byte) (any, error) {")
	writeLine("\tswitch method {")
	for request := range slices.Values(requestsAndNotifications) {
		methodName := methodNameIdentifier(request.Method)
		if request.Params == nil && len(request.ParamsArray) == 0 {
			writeLine(fmt.Sprintf("\tcase Method%s:", methodName))
			writeLine("\t\treturn unmarshalEmpty(data)")
			continue
		}
		if len(request.ParamsArray) > 0 {
			panic(fmt.Sprintf("Unexpected array type for request params: %v", request.ParamsArray))
		}
		resolved := resolveType(request.Params)
		writeLine(fmt.Sprintf("\tcase Method%s:", methodName))
		if resolved.Name == "any" {
			writeLine("\t\treturn unmarshalAny(data)")
		} else {
			writeLine(fmt.Sprintf("\t\treturn unmarshalPtrTo[%s](data)", resolved.Name))
		}
	}
	writeLine("\tdefault:")
	writeLine("\t\treturn unmarshalAny(data)")
	writeLine("\t}")
	writeLine("}")
	writeLine("")

	writeLine("func unmarshalResult(method Method, data []byte) (any, error) {")
	writeLine("\tswitch method {")
	for request := range slices.Values(model.Requests) {
		methodName := methodNameIdentifier(request.Method)
		responseTypeName := ""
		if request.TypeName != "" && strings.HasSuffix(request.TypeName, "Request") {
			responseTypeName = strings.TrimSuffix(request.TypeName, "Request") + "Response"
		} else {
			responseTypeName = methodName + "Response"
		}
		responseTypeName = goPublicIdentifier(responseTypeName)
		writeLine(fmt.Sprintf("\tcase Method%s:", methodName))
		writeLine(fmt.Sprintf("\t\treturn unmarshalValue[%s](data)", responseTypeName))
	}
	writeLine("\tdefault:")
	writeLine("\t\treturn unmarshalAny(data)")
	writeLine("\t}")
	writeLine("}")
	writeLine("")

	// Method constants map protocol method strings to typed Method values.
	writeLine("// Methods")
	writeLine("const (")
	for request := range slices.Values(requestsAndNotifications) {
		write(formatDocumentation(request.Documentation))
		methodName := methodNameIdentifier(request.Method)
		writeLine(fmt.Sprintf("\tMethod%s Method = \"%s\"", methodName, request.Method))
	}
	writeLine(")")
	writeLine("")

	writeLine("// Request response types")
	writeLine("")

	for request := range slices.Values(requestsAndNotifications) {
		methodName := methodNameIdentifier(request.Method)
		var responseTypeName string
		hasResult := false
		for i := range model.Requests {
			if model.Requests[i].Method == request.Method {
				hasResult = true
				if model.Requests[i].TypeName != "" && strings.HasSuffix(model.Requests[i].TypeName, "Request") {
					responseTypeName = strings.TrimSuffix(model.Requests[i].TypeName, "Request") + "Response"
				} else {
					responseTypeName = methodName + "Response"
				}
				break
			}
		}
		if hasResult {
			responseTypeName = goPublicIdentifier(responseTypeName)

			writeLine(fmt.Sprintf("// Response type for `%s`", request.Method))
			if request.Result != nil && request.Result.Kind == kindBase && request.Result.Name == "null" {
				writeLine(fmt.Sprintf("type %s = Null", responseTypeName))
			} else if request.Result != nil {
				resultType := resolveType(request.Result)
				goType := resultType.Name
				if resultType.NeedsPointer {
					goType = "*" + goType
				}
				writeLine(fmt.Sprintf("type %s = %s", responseTypeName, goType))
			}
			writeLine("")
		}

		if len(request.ParamsArray) > 0 {
			panic(fmt.Sprintf("Unexpected request params for %s: %v", methodName, request.ParamsArray))
		}
		paramType := request.Params
		paramGoType := "any"
		if paramType != nil {
			resolved := resolveType(paramType)
			paramGoType = resolved.Name
			if resolved.NeedsPointer {
				paramGoType = "*" + paramGoType
			}
		}
		writeLine(fmt.Sprintf("// Type mapping info for `%s`", request.Method))
		if hasResult {
			writeLine(fmt.Sprintf("var %sInfo = RequestInfo[%s, %s]{Method: Method%s}", methodName, paramGoType, responseTypeName, methodName))
		} else {
			writeLine(fmt.Sprintf("var %sInfo = NotificationInfo[%s]{Method: Method%s}", methodName, paramGoType, methodName))
		}
		writeLine("")
	}

	writeLine("// Union types")
	writeLine("")

	for i := 0; i < len(typeInfo.UnionTypes.keys); i++ {
		name := typeInfo.UnionTypes.keys[i]
		members, _ := typeInfo.UnionTypes.Get(name)
		writeLine(fmt.Sprintf("type %s struct {", name))
		uniqueTypeFields := NewOrderedMap[string]()
		for member := range slices.Values(members) {
			t := resolveType(member.Type)
			memberType := t.Name
			if _, ok := uniqueTypeFields.Get(memberType); !ok {
				fieldName := titleCase(member.Name)
				uniqueTypeFields.Set(memberType, fieldName)
				writeLine(fmt.Sprintf("\t%s *%s", fieldName, memberType))
			}
		}
		writeLine("}")
		writeLine("")

		type fieldEntry struct {
			FieldName string
			TypeName  string
		}
		fieldEntries := make([]fieldEntry, len(uniqueTypeFields.keys))
		for i, typeName := range uniqueTypeFields.keys {
			fieldEntries[i] = fieldEntry{
				FieldName: uniqueTypeFields.values[typeName],
				TypeName:  typeName,
			}
		}

		writeLine(fmt.Sprintf("var _ json.MarshalerTo = (*%s)(nil)", name))
		writeLine("")
		writeLine(fmt.Sprintf("func (o *%s) MarshalJSONTo(enc *jsontext.Encoder) error {", name))
		unionContainedNull := false
		for member := range slices.Values(members) {
			if member.ContainedNull {
				unionContainedNull = true
				break
			}
		}
		// Enforce that at most one union field is set before encoding.
		if unionContainedNull {
			write("\tassertAtMostOne(\"more than one element of " + name + " is set\", ")
		} else {
			write("\tassertOnlyOne(\"exactly one element of " + name + " should be set\", ")
		}
		for i, entry := range fieldEntries {
			if i > 0 {
				write(", ")
			}
			write("o." + entry.FieldName + " != nil")
		}
		writeLine(")")
		writeLine("")

		for entry := range slices.Values(fieldEntries) {
			writeLine(fmt.Sprintf("\tif o.%s != nil {", entry.FieldName))
			writeLine(fmt.Sprintf("\t\treturn json.MarshalEncode(enc, o.%s)", entry.FieldName))
			writeLine("\t}")
		}
		if unionContainedNull {
			writeLine("\treturn enc.WriteToken(jsontext.Null)")
		} else {
			writeLine("\tpanic(\"unreachable\")")
		}
		writeLine("}")
		writeLine("")

		writeLine(fmt.Sprintf("var _ json.UnmarshalerFrom = (*%s)(nil)", name))
		writeLine("")
		writeLine(fmt.Sprintf("func (o *%s) UnmarshalJSONFrom(dec *jsontext.Decoder) error {", name))
		writeLine(fmt.Sprintf("\t*o = %s{}", name))
		writeLine("")
		writeLine("\tdata, err := dec.ReadValue()")
		writeLine("\tif err != nil {")
		writeLine("\t\treturn err")
		writeLine("\t}")
		if unionContainedNull {
			writeLine("\tif string(data) == \"null\" {")
			writeLine("\t\treturn nil")
			writeLine("\t}")
			writeLine("")
		}
		// Try each union member in order until one succeeds.
		for entry := range slices.Values(fieldEntries) {
			writeLine(fmt.Sprintf("\tvar v%s %s", entry.FieldName, entry.TypeName))
			writeLine(fmt.Sprintf("\tif err := json.Unmarshal(data, &v%s); err == nil {", entry.FieldName))
			writeLine(fmt.Sprintf("\t\to.%s = &v%s", entry.FieldName, entry.FieldName))
			writeLine("\t\treturn nil")
			writeLine("\t}")
		}
		writeLine(fmt.Sprintf("\treturn fmt.Errorf(\"invalid %s: %%s\", data)", name))
		writeLine("}")
		writeLine("")
	}

	writeLine("// Literal types")
	writeLine("")

	for i := range len(typeInfo.LiteralTypes.keys) {
		value := typeInfo.LiteralTypes.keys[i]
		name, _ := typeInfo.LiteralTypes.Get(value)
		jsonValue, _ := json.Marshal(value)
		writeLine(fmt.Sprintf("// %s is a literal type for %s", name, string(jsonValue)))
		writeLine(fmt.Sprintf("type %s struct{}", name))
		writeLine("")
		writeLine(fmt.Sprintf("var _ json.MarshalerTo = %s{}", name))
		writeLine("")
		writeLine(fmt.Sprintf("func (o %s) MarshalJSONTo(enc *jsontext.Encoder) error {", name))
		writeLine(fmt.Sprintf("\treturn enc.WriteValue(jsontext.Value(`%s`))", string(jsonValue)))
		writeLine("}")
		writeLine("")
		writeLine(fmt.Sprintf("var _ json.UnmarshalerFrom = &%s{}", name))
		writeLine("")
		writeLine(fmt.Sprintf("func (o *%s) UnmarshalJSONFrom(dec *jsontext.Decoder) error {", name))
		writeLine("\tv, err := dec.ReadValue();")
		writeLine("\tif err != nil {")
		writeLine("\t\treturn err")
		writeLine("\t}")
		writeLine(fmt.Sprintf("\tif string(v) != `%s` {", string(jsonValue)))
		writeLine(fmt.Sprintf("\t\treturn fmt.Errorf(\"expected %s value %%s, got %%s\", `%s`, v)", name, string(jsonValue)))
		writeLine("\t}")
		writeLine("\treturn nil")
		writeLine("}")
		writeLine("")
	}

	clientCapsStructure := findStructure(model.Structures, "ClientCapabilities")
	if clientCapsStructure != nil {
		writeLine("// Helper function for dereferencing pointers with zero value fallback")
		writeLine("func derefOr[T any](v *T) T {")
		writeLine("\tif v != nil {")
		writeLine("\t\treturn *v")
		writeLine("\t}")
		writeLine("\tvar zero T")
		writeLine("\treturn zero")
		writeLine("}")
		writeLine("")

		deps := collectStructureDependencies(model, clientCapsStructure, nil)
		unique := NewOrderedMap[*Structure]()
		for dep := range slices.Values(deps) {
			if dep != nil {
				unique.Set(dep.Name, dep)
			}
		}
		for name := range slices.Values(unique.keys) {
			dep := unique.values[name]
			for line := range slices.Values(generateResolvedTypeAndHelper(model, dep, false)) {
				writeLine(line)
			}
		}

		writeLine("// ResolvedClientCapabilities is a version of ClientCapabilities where all nested")
		writeLine("// fields are values (not pointers), making it easier to access deeply nested capabilities.")
		writeLine("// Use ResolveClientCapabilities to convert from ClientCapabilities.")
		if clientCapsStructure.Documentation != "" {
			writeLine("//")
			typeDoc := formatDocumentation(clientCapsStructure.Documentation)
			for line := range strings.SplitSeq(strings.TrimRight(typeDoc, "\n"), "\n") {
				writeLine(line)
			}
		}
		for line := range slices.Values(generateResolvedTypeAndHelper(model, clientCapsStructure, true)) {
			writeLine(line)
		}
	}

	return w.b.String()
}

// findStructure returns the structure with the given name.
func findStructure(structures []Structure, name string) *Structure {
	for i := range structures {
		if structures[i].Name == name {
			return &structures[i]
		}
	}
	return nil
}

// hasSomeProp reports whether structure contains a required property with the given type.
func hasSomeProp(structure *Structure, propName, propTypeName string) bool {
	for p := range slices.Values(structure.Properties) {
		if p.Optional {
			continue
		}
		if p.Name == propName && p.Type.Kind == kindReference && p.Type.Name == propTypeName {
			return true
		}
	}
	return false
}

// hasTextDocumentURI reports whether structure has a textDocument identifier property.
func hasTextDocumentURI(structure *Structure) bool {
	return hasSomeProp(structure, "textDocument", "TextDocumentIdentifier")
}

// hasTextDocumentPosition reports whether structure has a position property.
func hasTextDocumentPosition(structure *Structure) bool {
	return hasSomeProp(structure, "position", "Position")
}

// jsonNumber is an interface representation of the json v1 Number type.
type jsonNumber interface {
	Float64() (float64, error)
	Int64() (int64, error)
}

// toNumber coerces common JSON number forms into float64.
func toNumber(v any) (float64, bool) {
	switch n := v.(type) {
	case float64:
		return n, true
	case int:
		return float64(n), true
	case jsonNumber:
		f, err := n.Float64()
		if err == nil {
			return f, true
		}
	case string:
		var num float64
		if err := json.Unmarshal([]byte(n), &num); err == nil {
			return num, true
		}
	}
	return 0, false
}

// enumRun represents a contiguous run of enum values.
type enumRun struct {
	Names  []string
	Values []float64
}

// NumericValue stores an enum value with derived numeric metadata.
type NumericValue struct {
	Value         string
	NumericValue  float64
	Name          string
	Identifier    string
	Documentation string
}

// sortByNumericValue orders values by NumericValue ascending.
func sortByNumericValue(values []NumericValue) {
	for i := range values {
		for j := i + 1; j < len(values); j++ {
			if values[j].NumericValue < values[i].NumericValue {
				values[i], values[j] = values[j], values[i]
			}
		}
	}
}

// splitNumeric groups values into contiguous numeric runs.
func splitNumeric(values []NumericValue) []enumRun {
	if len(values) == 0 {
		return nil
	}

	runs := []enumRun{
		{
			Names:  []string{values[0].Name},
			Values: []float64{values[0].NumericValue},
		},
	}
	for i := 1; i < len(values); i++ {
		prev := values[i-1].NumericValue
		if values[i].NumericValue == prev+1 {
			runs[len(runs)-1].Names = append(runs[len(runs)-1].Names, values[i].Name)
			runs[len(runs)-1].Values = append(runs[len(runs)-1].Values, values[i].NumericValue)
		} else {
			runs = append(runs, enumRun{Names: []string{values[i].Name}, Values: []float64{values[i].NumericValue}})
		}
	}

	return runs
}

// structMapEntry binds a generated struct name to an output file.
type structMapEntry struct {
	Name string `json:"name"`
	File string `json:"file"`
}

// structFilesFromMap loads the struct-to-file mapping from JSON.
func structFilesFromMap(path string) (map[string]string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	var entries []structMapEntry
	if err := json.Unmarshal(data, &entries); err != nil {
		return nil, err
	}
	if len(entries) == 0 {
		return nil, errors.New("struct map is empty")
	}

	structFiles := make(map[string]string, len(entries))
	for i, entry := range entries {
		if entry.Name == "" || entry.File == "" {
			return nil, fmt.Errorf("struct map entry %d missing name or file", i)
		}
		if prev, ok := structFiles[entry.Name]; ok {
			if prev == entry.File {
				return nil, fmt.Errorf("duplicate struct map entry for %q", entry.Name)
			}
			return nil, fmt.Errorf("conflicting struct map entry for %q: %q vs %q", entry.Name, prev, entry.File)
		}
		structFiles[entry.Name] = entry.File
	}

	return structFiles, nil
}

// splitGenDecl ensures each type/value spec has its own GenDecl with proper docs.
func splitGenDecl(decl *ast.GenDecl) []*ast.GenDecl {
	if len(decl.Specs) <= 1 {
		return []*ast.GenDecl{decl}
	}
	parts := make([]*ast.GenDecl, 0, len(decl.Specs))
	for _, spec := range decl.Specs {
		next := &ast.GenDecl{
			Tok:    decl.Tok,
			TokPos: decl.TokPos,
			Specs:  []ast.Spec{spec},
		}

		switch s := spec.(type) {
		case *ast.TypeSpec:
			if s.Doc != nil {
				next.Doc = s.Doc
				s.Doc = nil
			} else {
				next.Doc = decl.Doc
			}
		case *ast.ValueSpec:
			if s.Doc != nil {
				next.Doc = s.Doc
				s.Doc = nil
			} else {
				next.Doc = decl.Doc
			}
		default:
			next.Doc = decl.Doc
		}

		parts = append(parts, next)
	}

	return parts
}

// structNameFromAssertion detects json.(Un)Marshaler assertions for a struct type.
// It understands pointer, value, and composite literal forms used in generated code.
func structNameFromAssertion(spec *ast.ValueSpec) (string, bool) {
	if len(spec.Names) != 1 || spec.Names[0].Name != "_" {
		return "", false
	}
	sel, ok := spec.Type.(*ast.SelectorExpr)
	if !ok {
		return "", false
	}
	pkgIdent, ok := sel.X.(*ast.Ident)
	if !ok || pkgIdent.Name != "json" {
		return "", false
	}
	if sel.Sel == nil || (sel.Sel.Name != "MarshalerTo" && sel.Sel.Name != "UnmarshalerFrom") {
		return "", false
	}
	if len(spec.Values) != 1 {
		return "", false
	}

	switch v := spec.Values[0].(type) {
	case *ast.CallExpr:
		// Matches var _ json.MarshalerTo = (*T)(nil).
		if len(v.Args) != 1 {
			return "", false
		}
		parens, ok := v.Fun.(*ast.ParenExpr)
		if !ok {
			return "", false
		}
		star, ok := parens.X.(*ast.StarExpr)
		if !ok {
			return "", false
		}
		ident, ok := star.X.(*ast.Ident)
		if !ok {
			return "", false
		}
		return ident.Name, true

	case *ast.UnaryExpr:
		// Matches var _ json.MarshalerTo = &T{}.
		if v.Op != token.AND {
			return "", false
		}
		lit, ok := v.X.(*ast.CompositeLit)
		if !ok {
			return "", false
		}
		ident, ok := lit.Type.(*ast.Ident)
		if !ok {
			return "", false
		}
		return ident.Name, true

	case *ast.CompositeLit:
		// Matches var _ json.MarshalerTo = T{}.
		ident, ok := v.Type.(*ast.Ident)
		if !ok {
			return "", false
		}
		return ident.Name, true

	default:
		return "", false
	}
}

// filterComments keeps only comment groups that belong to the assigned decls.
// This prevents comments from drifting to unrelated files after splitting.
func filterComments(file *ast.File, decls []ast.Decl) []*ast.CommentGroup {
	if len(file.Comments) == 0 || len(decls) == 0 {
		return nil
	}

	ranges := make([][2]token.Pos, len(decls))
	for i, decl := range decls {
		ranges[i] = [2]token.Pos{decl.Pos(), decl.End()}
	}

	var filtered []*ast.CommentGroup
	for _, group := range file.Comments {
		for _, r := range ranges {
			if group.Pos() >= r[0] && group.End() <= r[1] {
				filtered = append(filtered, group)
				break
			}
		}
	}

	return filtered
}

// receiverTypeName extracts the named receiver type so methods can follow their structs.
func receiverTypeName(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		if ident, ok := t.X.(*ast.Ident); ok {
			return ident.Name
		}
	}
	return ""
}

// generateFileSources splits a generated file into multiple files by struct mapping.
func generateFileSources(src []byte, structFiles map[string]string, defaultFile string) (map[string][]byte, error) {
	if defaultFile == "" {
		return nil, errors.New("default file is empty")
	}
	if len(structFiles) == 0 {
		return nil, errors.New("struct map is empty")
	}

	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "generated.go", src, parser.ParseComments)
	if err != nil {
		return nil, err
	}

	// Start with the default file; structs will be routed by structFiles.
	fileDecls := map[string][]ast.Decl{
		defaultFile: nil,
	}
	missingStructs := make(map[string]struct{})

	addDecl := func(fileName string, decl ast.Decl) {
		fileDecls[fileName] = append(fileDecls[fileName], decl)
	}

	// Route declarations to their target files based on struct ownership.
	for _, decl := range file.Decls {
		if gen, ok := decl.(*ast.GenDecl); ok && gen.Tok == token.IMPORT {
			// Imports are regenerated per output file.
			continue
		}

		switch d := decl.(type) {
		case *ast.GenDecl:
			for _, split := range splitGenDecl(d) {
				switch split.Tok {
				case token.TYPE:
					spec, ok := split.Specs[0].(*ast.TypeSpec)
					if !ok {
						addDecl(defaultFile, split)
						continue
					}
					if _, ok := spec.Type.(*ast.StructType); ok {
						target, ok := structFiles[spec.Name.Name]
						if !ok {
							missingStructs[spec.Name.Name] = struct{}{}
							continue
						}
						addDecl(target, split)
						continue
					}
					addDecl(defaultFile, split)

				case token.VAR:
					if spec, ok := split.Specs[0].(*ast.ValueSpec); ok {
						if structName, ok := structNameFromAssertion(spec); ok {
							if target, ok := structFiles[structName]; ok {
								addDecl(target, split)
								continue
							}
						}
					}
					addDecl(defaultFile, split)

				default:
					addDecl(defaultFile, split)
				}
			}

		case *ast.FuncDecl:
			if d.Recv != nil && len(d.Recv.List) > 0 {
				if recvName := receiverTypeName(d.Recv.List[0].Type); recvName != "" {
					if target, ok := structFiles[recvName]; ok {
						addDecl(target, d)
						continue
					}
				}
			}
			addDecl(defaultFile, d)

		default:
			addDecl(defaultFile, d)
		}
	}

	if len(missingStructs) > 0 {
		missing := make([]string, 0, len(missingStructs))
		for name := range missingStructs {
			missing = append(missing, name)
		}
		slices.Sort(missing)
		return nil, fmt.Errorf("structs missing from struct map: %s", strings.Join(missing, ", "))
	}

	importPaths := map[string]string{
		"fmt":      "fmt",
		"strings":  "strings",
		"json":     "github.com/go-json-experiment/json",
		"jsontext": "github.com/go-json-experiment/json/jsontext",
		"uri":      "go.lsp.dev/uri",
	}
	importOrder := []string{"fmt", "strings", "json", "jsontext", "uri"}

	outputs := make(map[string][]byte, len(fileDecls))
	for name, decls := range fileDecls {
		// Compute the minimal import set by scanning selector expressions in decls.
		usedImports := make(map[string]struct{})
		for _, decl := range decls {
			ast.Inspect(decl, func(n ast.Node) bool {
				sel, ok := n.(*ast.SelectorExpr)
				if !ok {
					return true
				}
				ident, ok := sel.X.(*ast.Ident)
				if !ok {
					return true
				}
				if _, ok := importPaths[ident.Name]; ok {
					usedImports[ident.Name] = struct{}{}
				}
				return true
			})
		}

		var importNames []string
		for _, importName := range importOrder {
			if _, ok := usedImports[importName]; ok {
				importNames = append(importNames, importName)
			}
		}
		if len(usedImports) != len(importNames) {
			var remaining []string
			for importName := range usedImports {
				if !slices.Contains(importNames, importName) {
					remaining = append(remaining, importName)
				}
			}
			slices.Sort(remaining)
			importNames = append(importNames, remaining...)
		}

		var specs []*ast.ImportSpec
		if len(importNames) > 0 {
			specs = make([]*ast.ImportSpec, 0, len(importNames))
			for _, importName := range importNames {
				path := importPaths[importName]
				specs = append(specs, &ast.ImportSpec{
					Path: &ast.BasicLit{Kind: token.STRING, Value: strconv.Quote(path)},
				})
			}
		}

		outFile := &ast.File{
			Name:     ast.NewIdent("protocol"),
			Decls:    decls,
			Comments: filterComments(file, decls),
		}
		if len(specs) > 0 {
			importDecl := &ast.GenDecl{
				Tok:   token.IMPORT,
				Specs: make([]ast.Spec, len(specs)),
			}
			for i, spec := range specs {
				importDecl.Specs[i] = spec
			}
			outFile.Decls = append([]ast.Decl{importDecl}, outFile.Decls...)
			outFile.Imports = specs
		}

		var buf bytes.Buffer
		if err := format.Node(&buf, fset, outFile); err != nil {
			return nil, err
		}

		formatted, err := gofumpt.Source(buf.Bytes(), gofumpt.Options{
			LangVersion: "go1.25",
			ExtraRules:  true,
		})
		if err != nil {
			return nil, err
		}

		outputs[name] = append([]byte(generatedHeader), formatted...)
	}

	return outputs, nil
}

// main is the entry point for lspgen.
func main() {
	_, filename, _, ok := runtime.Caller(0)
	if !ok {
		panic("failed to get current filename")
	}
	baseDir := filepath.Dir(filename)
	repoRoot := filepath.Dir(filepath.Dir(baseDir))
	metaModelPath := filepath.Join(baseDir, "metaModel.json")
	structMapPath := filepath.Join(baseDir, "struct-map.json")

	metaModelData, err := os.ReadFile(metaModelPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Meta model file not found; did you forget to run fetchModel.mts?\n")
		os.Exit(1)
	}

	var model MetaModel
	if err := json.Unmarshal(metaModelData, &model); err != nil {
		fmt.Fprintln(os.Stderr, err.Error())
		os.Exit(1)
	}

	customStructures = customStructures[:]
	registerOptionsUnionType = nil
	typeInfo = newTypeInfo()

	if err := patchAndPreprocessModel(&model); err != nil {
		fmt.Fprintln(os.Stderr, err.Error())
		os.Exit(1)
	}
	collectTypeDefinitions(&model)
	generatedCode := generateCode(&model)

	structFiles, err := structFilesFromMap(structMapPath)
	if err != nil {
		fmt.Fprintln(os.Stderr, err.Error())
		os.Exit(1)
	}

	fileSources, err := generateFileSources([]byte(generatedCode), structFiles, "lsp.go")
	if err != nil {
		fmt.Fprintln(os.Stderr, err.Error())
		os.Exit(1)
	}

	fileNames := make([]string, len(fileSources))
	i := 0
	for name := range fileSources {
		fileNames[i] = name
		i++
	}
	slices.Sort(fileNames)

	if len(fileNames) == 0 {
		fmt.Printf("No files generated\n")
		return
	}

	for _, name := range fileNames {
		outPath := filepath.Join(repoRoot, name)
		if err := os.WriteFile(outPath, fileSources[name], 0o644); err != nil {
			fmt.Fprintln(os.Stderr, err.Error())
			os.Exit(1)
		}
		fmt.Printf("Successfully generated %s\n", filepath.Join(repoRoot, name))
	}
}
