// Copyright 2026 The Go Language Server Authors.
// SPDX-License-Identifier: BSD-3-Clause

package main

import (
	"fmt"
	"sort"
	"strconv"
	"strings"

	"github.com/go-json-experiment/json"
	"github.com/go-json-experiment/json/jsontext"
	gofumpt "mvdan.cc/gofumpt/format"
)

type fileImports struct {
	paths map[string]string
}

func newFileImports() *fileImports {
	return &fileImports{paths: make(map[string]string)}
}

func (f *fileImports) add(path string) {
	if path == "" {
		return
	}

	f.paths[path] = ""
}

func (f *fileImports) lines() []string {
	if len(f.paths) == 0 {
		return nil
	}

	paths := make([]string, 0, len(f.paths))
	for path := range f.paths {
		paths = append(paths, path)
	}
	sort.Strings(paths)

	lines := make([]string, 0, len(paths))
	for _, path := range paths {
		alias := f.paths[path]
		if alias == "" {
			lines = append(lines, fmt.Sprintf("\t%q", path))
			continue
		}
		lines = append(lines, fmt.Sprintf("\t%s %q", alias, path))
	}

	return lines
}

func (g *generator) renderFiles(defs map[string]typeDef) (map[string][]byte, error) {
	fileDefs := make(map[string][]typeDef)
	for name, def := range defs {
		file := g.cfg.fallbackFile
		if mapped, ok := g.structMapByName[name]; ok {
			file = mapped
		}
		fileDefs[file] = append(fileDefs[file], def)
	}

	if g.needsUnionHelpers() {
		if _, ok := fileDefs[g.cfg.fallbackFile]; !ok {
			fileDefs[g.cfg.fallbackFile] = nil
		}
	}

	out := make(map[string][]byte, len(fileDefs))
	for file, defs := range fileDefs {
		sort.Slice(defs, func(i, j int) bool {
			left := defs[i].Name
			right := defs[j].Name
			li, lok := g.structMapOrder[left]
			ri, rok := g.structMapOrder[right]
			if lok && rok {
				return li < ri
			}
			if lok != rok {
				return lok
			}
			return left < right
		})
		bytes, err := g.renderFile(file, defs)
		if err != nil {
			return nil, err
		}
		out[file] = bytes
	}

	return out, nil
}

func (g *generator) renderFile(name string, defs []typeDef) ([]byte, error) {
	imports := newFileImports()
	var body strings.Builder

	for _, def := range defs {
		if err := g.renderType(&body, imports, def); err != nil {
			return nil, err
		}
	}

	if name == g.cfg.fallbackFile && g.needsUnionHelpers() {
		body.WriteString(g.renderUnionHelpers(imports))
	}

	header := []string{
		"// Copyright 2026 The Go Language Server Authors.",
		"// SPDX-License-Identifier: BSD-3-Clause",
		"",
		"// Code generated by lspgen; DO NOT EDIT.",
		"",
		"package " + g.cfg.packageName,
		"",
	}

	var out strings.Builder
	out.WriteString(joinNonEmpty(header))

	if importLines := imports.lines(); len(importLines) > 0 {
		out.WriteString("import (\n")
		out.WriteString(joinNonEmpty(importLines))
		out.WriteString(")\n\n")
	}
	out.WriteString(body.String())

	formatted, err := gofumpt.Source([]byte(out.String()), gofumpt.Options{
		LangVersion: "go1.25",
		ExtraRules:  true,
	})
	if err != nil {
		return nil, fmt.Errorf("format %s: %w", name, err)
	}

	return formatted, nil
}

func (g *generator) renderType(b *strings.Builder, imports *fileImports, def typeDef) error {
	switch def.Kind {
	case typeDefStruct:
		return g.renderStruct(b, def.Name, def.Struct, typeOptions{})
	case typeDefResolvedStruct:
		return g.renderResolvedAlias(b, def)
	case typeDefEnum:
		return g.renderEnum(b, def)
	case typeDefAlias:
		return g.renderAlias(b, imports, def)
	case typeDefUnion:
		return g.renderUnion(b, imports, def)
	case typeDefStringLiteral:
		return g.renderStringLiteral(b, imports, def)
	case typeDefTuple:
		return g.renderTuple(b)
	case typeDefEmptyObject:
		return g.renderEmptyObject(b)
	case typeDefNull:
		return g.renderNull(b, imports)
	default:
		return fmt.Errorf("unsupported typeDef kind %v", def.Kind)
	}
}

func (g *generator) renderStruct(b *strings.Builder, name string, s *structure, opts typeOptions) error {
	doc := adjustStructDoc(name, s.Documentation)
	lines := docLines(doc, s.Since, s.Deprecated, s.Proposed)
	for _, line := range commentLines(lines) {
		b.WriteString(line)
		b.WriteByte('\n')
	}
	b.WriteString("type " + name + " struct {\n")

	for _, ext := range s.Extends {
		typeName, err := g.goType(ext, opts)
		if err != nil {
			return err
		}
		b.WriteString("\t" + typeName + "\n")
	}

	for _, mixin := range s.Mixins {
		typeName, err := g.goType(mixin, opts)
		if err != nil {
			return err
		}
		b.WriteString("\t" + typeName + "\n")
	}

	for _, prop := range s.Properties {
		propLines := docLines(prop.Documentation, prop.Since, prop.Deprecated, prop.Proposed)
		comment := commentLines(propLines)
		for _, line := range comment {
			b.WriteString("\t" + line)
			b.WriteByte('\n')
		}
		if len(comment) > 0 {
			b.WriteByte('\n')
		}
		fieldName := goName(prop.Name)
		fieldType, err := g.propertyGoType(name, prop, opts)
		if err != nil {
			return err
		}
		if prop.Optional && g.shouldPointer(prop.Type) {
			fieldType = "*" + fieldType
		}
		omitEmpty := prop.Optional && g.isPrimitiveGoType(prop.Type)
		tag := jsonTag(prop.Name, prop.Optional, omitEmpty)
		b.WriteString("\t" + fieldName + " " + fieldType + " `" + tag + "`\n")
	}
	b.WriteString("}\n\n")

	return nil
}

func adjustStructDoc(name, doc string) string {
	if doc == "" {
		return doc
	}

	lines := strings.Split(doc, "\n")
	first := lines[0]
	trimmed := strings.TrimSpace(first)
	if trimmed == "" || strings.HasPrefix(trimmed, name+" ") || trimmed == name || strings.HasPrefix(trimmed, "@") {
		return doc
	}

	leading := first[:len(first)-len(strings.TrimLeft(first, " \t"))]
	if article, rest, ok := leadingArticle(trimmed); ok {
		newFirst := leading + name + " " + strings.ToLower(article)
		if rest != "" {
			newFirst += " " + rest
		}
		lines[0] = newFirst
		return strings.Join(lines, "\n")
	}

	lines[0] = leading + name + " " + lowerLeadingWord(trimmed)

	return strings.Join(lines, "\n")
}

func lowerLeadingWord(line string) string {
	if line == "" {
		return line
	}

	if len(line) == 1 {
		if line[0] >= 'A' && line[0] <= 'Z' {
			return string(line[0] + ('a' - 'A'))
		}
		return line
	}
	if line[0] >= 'A' && line[0] <= 'Z' && line[1] >= 'a' && line[1] <= 'z' {
		return string(line[0]+('a'-'A')) + line[1:]
	}

	return line
}

func leadingArticle(line string) (string, string, bool) {
	articles := []string{"A ", "An ", "The ", "a ", "an ", "the "}
	for _, article := range articles {
		if strings.HasPrefix(line, article) {
			return strings.TrimSpace(article), line[len(article):], true
		}
	}

	return "", "", false
}

func (g *generator) renderResolvedAlias(b *strings.Builder, def typeDef) error {
	lines := docLines("Resolved"+def.ResolvedFrom+" provides a resolved view of "+def.ResolvedFrom+".", "", "", false)
	for _, line := range commentLines(lines) {
		b.WriteString(line)
		b.WriteByte('\n')
	}
	b.WriteString("type " + def.Name + " = " + def.ResolvedFrom + "\n\n")

	return nil
}

func (g *generator) renderEnum(b *strings.Builder, def typeDef) error {
	enum := def.Enum
	lines := docLines(enum.Documentation, enum.Since, enum.Deprecated, enum.Proposed)
	for _, line := range commentLines(lines) {
		b.WriteString(line)
		b.WriteByte('\n')
	}
	baseType, err := g.goType(enum.Type, typeOptions{})
	if err != nil {
		return err
	}
	b.WriteString("type " + def.Name + " " + baseType + "\n\n")

	b.WriteString("const (\n")
	for _, val := range enum.Values {
		valueLines := docLines(val.Documentation, val.Since, val.Deprecated, val.Proposed)
		for _, line := range commentLines(valueLines) {
			b.WriteString("\t" + line)
			b.WriteByte('\n')
		}
		literal, err := enumValueLiteral(enum.Type, val.Value)
		if err != nil {
			return err
		}
		name := formatConstName(def.Name, val.Name)
		b.WriteString("\t" + name + " " + def.Name + " = " + literal + "\n")
	}
	b.WriteString(")\n\n")

	return nil
}

func enumValueLiteral(t metaType, value jsontext.Value) (string, error) {
	switch t.Kind {
	case metaTypeBase:
		switch t.Name {
		case "string", "DocumentUri", "URI":
			var s string
			if err := json.Unmarshal(value, &s); err != nil {
				return "", err
			}
			return strconv.Quote(s), nil

		case "integer":
			var i int32
			if err := json.Unmarshal(value, &i); err != nil {
				return "", err
			}
			return strconv.FormatInt(int64(i), 10), nil

		case "uinteger":
			var u uint32
			if err := json.Unmarshal(value, &u); err != nil {
				return "", err
			}
			return strconv.FormatUint(uint64(u), 10), nil

		case "decimal":
			var f float64
			if err := json.Unmarshal(value, &f); err != nil {
				return "", err
			}
			return strconv.FormatFloat(f, 'f', -1, 64), nil

		default:
			var raw jsontext.Value
			if err := json.Unmarshal(value, &raw); err != nil {
				return "", err
			}
			return string(raw), nil
		}

	default:
		return "", fmt.Errorf("unsupported enum base type %q", t.Kind)
	}
}

func (g *generator) renderAlias(b *strings.Builder, imports *fileImports, def typeDef) error {
	alias := def.Alias
	lines := docLines(alias.Documentation, alias.Since, alias.Deprecated, alias.Proposed)
	for _, line := range commentLines(lines) {
		b.WriteString(line)
		b.WriteByte('\n')
	}

	override := aliasOverrideType(def.Name)
	if override != "" {
		if strings.HasPrefix(override, "uri.") {
			imports.add("go.lsp.dev/uri")
		}
		b.WriteString("type " + def.Name + " = " + override + "\n\n")
		return nil
	}

	aliasType, err := g.goType(alias.Type, typeOptions{})
	if err != nil {
		return err
	}

	b.WriteString("type " + def.Name + " " + aliasType + "\n\n")

	return nil
}

func (g *generator) renderUnion(b *strings.Builder, imports *fileImports, def typeDef) error {
	imports.add("errors")
	imports.add("github.com/go-json-experiment/json")
	imports.add("github.com/go-json-experiment/json/jsontext")

	union := def.Union
	variants, err := g.unionVariants(*union)
	if err != nil {
		return err
	}

	b.WriteString("type " + def.Name + " struct {\n")
	for _, v := range variants {
		b.WriteString("\t" + v.FieldName + " *" + v.TypeName + " `json:\"-\"`\n")
	}
	b.WriteString("}\n\n")

	b.WriteString("func (u " + def.Name + ") MarshalJSON() ([]byte, error) {\n")
	b.WriteString("\tvar (\n\t\tdata []byte\n\t\tcount int\n\t)\n")
	for _, v := range variants {
		b.WriteString("\tif u." + v.FieldName + " != nil {\n")
		b.WriteString("\t\tcount++\n")
		b.WriteString("\t\tvar err error\n")
		b.WriteString("\t\tdata, err = json.Marshal(u." + v.FieldName + ")\n")
		b.WriteString("\t\tif err != nil {\n\t\t\treturn nil, err\n\t\t}\n")
		b.WriteString("\t}\n")
	}
	b.WriteString("\tswitch count {\n")
	b.WriteString("\tcase 0:\n\t\treturn nil, errors.New(\"" + def.Name + ": no value set\")\n")
	b.WriteString("\tcase 1:\n\t\treturn data, nil\n")
	b.WriteString("\tdefault:\n\t\treturn nil, errors.New(\"" + def.Name + ": multiple values set\")\n\t}\n")
	b.WriteString("}\n\n")

	b.WriteString("func (u " + def.Name + ") MarshalJSONTo(enc *jsontext.Encoder) error {\n")
	b.WriteString("\tdata, err := u.MarshalJSON()\n")
	b.WriteString("\tif err != nil {\n\t\treturn err\n\t}\n")
	b.WriteString("\treturn enc.WriteValue(jsontext.Value(data))\n")
	b.WriteString("}\n\n")

	b.WriteString("func (u *" + def.Name + ") UnmarshalJSON(data []byte) error {\n")
	b.WriteString("\tvar value jsontext.Value\n")
	b.WriteString("\tif err := json.Unmarshal(data, &value); err != nil {\n\t\treturn err\n\t}\n")
	b.WriteString("\treturn u.unmarshalJSONValue(value)\n")
	b.WriteString("}\n\n")

	b.WriteString("func (u *" + def.Name + ") UnmarshalJSONFrom(dec *jsontext.Decoder) error {\n")
	b.WriteString("\tvalue, err := dec.ReadValue()\n")
	b.WriteString("\tif err != nil {\n\t\treturn err\n\t}\n")
	b.WriteString("\treturn u.unmarshalJSONValue(value)\n")
	b.WriteString("}\n\n")

	b.WriteString("func (u *" + def.Name + ") unmarshalJSONValue(value jsontext.Value) error {\n")
	b.WriteString("\t*u = " + def.Name + "{}\n")
	b.WriteString("\tkind := value.Kind()\n")
	b.WriteString("\tif kind == 'n' {\n")
	nullIndex := -1
	for i, v := range variants {
		if v.Meta.Kind == metaTypeBase && v.Meta.Name == "null" {
			nullIndex = i
			break
		}
	}
	if nullIndex >= 0 {
		v := variants[nullIndex]
		b.WriteString("\t\tu." + v.FieldName + " = new(" + v.TypeName + ")\n")
		b.WriteString("\t\treturn nil\n")
	} else {
		for _, v := range variants {
			if v.Mask&kindMaskNull == 0 {
				continue
			}
			b.WriteString("\t\tu." + v.FieldName + " = new(" + v.TypeName + ")\n")
			b.WriteString("\t\treturn nil\n")
			break
		}
	}
	b.WriteString("\t}\n")

	if g.hasDiscriminators(variants) {
		b.WriteString("\tif kind == '{' {\n")
		b.WriteString("\t\tobj, err := decodeObject(value)\n")
		b.WriteString("\t\tif err != nil {\n\t\t\treturn err\n\t\t}\n")
		for _, v := range variants {
			if len(v.Discriminators) == 0 {
				continue
			}
			conds := make([]string, 0, len(v.Discriminators))
			for _, disc := range v.Discriminators {
				conds = append(conds, fmt.Sprintf("objectFieldEquals(obj, %q, %q)", disc.JSONName, disc.Value))
			}
			b.WriteString("\t\tif " + strings.Join(conds, " && ") + " {\n")
			b.WriteString("\t\t\tvar v " + v.TypeName + "\n")
			b.WriteString("\t\t\tif err := json.Unmarshal(value, &v); err != nil {\n\t\t\t\treturn err\n\t\t\t}\n")
			b.WriteString("\t\t\tu." + v.FieldName + " = &v\n")
			b.WriteString("\t\t\treturn nil\n")
			b.WriteString("\t\t}\n")
		}
		b.WriteString("\t}\n")
	}

	for _, v := range variants {
		b.WriteString("\tif unionKindMatches(kind, " + fmt.Sprintf("%d", v.Mask) + ") {\n")
		b.WriteString("\t\tvar v " + v.TypeName + "\n")
		b.WriteString("\t\tif err := json.Unmarshal(value, &v); err == nil {\n")
		b.WriteString("\t\t\tu." + v.FieldName + " = &v\n")
		b.WriteString("\t\t\treturn nil\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t}\n")
	}
	b.WriteString("\treturn errors.New(\"" + def.Name + ": no matching type\")\n")
	b.WriteString("}\n\n")

	return nil
}

func (g *generator) hasDiscriminators(variants []unionVariant) bool {
	for _, v := range variants {
		if len(v.Discriminators) > 0 {
			return true
		}
	}

	return false
}

func (g *generator) renderStringLiteral(b *strings.Builder, imports *fileImports, def typeDef) error {
	imports.add("errors")
	imports.add("github.com/go-json-experiment/json")
	imports.add("github.com/go-json-experiment/json/jsontext")

	value := def.StringValue
	constName := def.Name + "Value"
	lines := docLines(def.Name+" represents the string literal \""+value+"\".", "", "", false)
	for _, line := range commentLines(lines) {
		b.WriteString(line)
		b.WriteByte('\n')
	}
	b.WriteString("type " + def.Name + " struct{}\n\n")
	b.WriteString("const " + constName + " = " + strconv.Quote(value) + "\n\n")

	b.WriteString("func (" + def.Name + ") MarshalJSON() ([]byte, error) {\n")
	b.WriteString("\treturn json.Marshal(" + constName + ")\n")
	b.WriteString("}\n\n")

	b.WriteString("func (" + def.Name + ") MarshalJSONTo(enc *jsontext.Encoder) error {\n")
	b.WriteString("\treturn enc.WriteToken(jsontext.String(" + constName + "))\n")
	b.WriteString("}\n\n")

	b.WriteString("func (s *" + def.Name + ") UnmarshalJSON(data []byte) error {\n")
	b.WriteString("\tvar v string\n")
	b.WriteString("\tif err := json.Unmarshal(data, &v); err != nil {\n\t\treturn err\n\t}\n")
	b.WriteString("\tif v != " + constName + " {\n")
	b.WriteString("\t\treturn errors.New(\"" + def.Name + ": invalid value\")\n\t}\n")
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n\n")

	b.WriteString("func (s *" + def.Name + ") UnmarshalJSONFrom(dec *jsontext.Decoder) error {\n")
	b.WriteString("\tvalue, err := dec.ReadValue()\n")
	b.WriteString("\tif err != nil {\n\t\treturn err\n\t}\n")
	b.WriteString("\treturn s.UnmarshalJSON(value)\n")
	b.WriteString("}\n\n")

	return nil
}

func (g *generator) renderTuple(b *strings.Builder) error {
	lines := docLines("Tuple represents a fixed-length array from the LSP meta model.", "", "", false)
	for _, line := range commentLines(lines) {
		b.WriteString(line)
		b.WriteByte('\n')
	}
	b.WriteString("type Tuple []any\n\n")

	return nil
}

func (g *generator) renderEmptyObject(b *strings.Builder) error {
	lines := docLines("EmptyObject represents an empty JSON object.", "", "", false)
	for _, line := range commentLines(lines) {
		b.WriteString(line)
		b.WriteByte('\n')
	}
	b.WriteString("type EmptyObject struct{}\n\n")

	return nil
}

func (g *generator) renderNull(b *strings.Builder, imports *fileImports) error {
	imports.add("errors")
	imports.add("github.com/go-json-experiment/json")
	imports.add("github.com/go-json-experiment/json/jsontext")

	lines := docLines("Null represents the JSON null value.", "", "", false)
	for _, line := range commentLines(lines) {
		b.WriteString(line)
		b.WriteByte('\n')
	}
	b.WriteString("type Null struct{}\n\n")

	b.WriteString("func (Null) MarshalJSON() ([]byte, error) {\n")
	b.WriteString("\treturn []byte(\"null\"), nil\n")
	b.WriteString("}\n\n")

	b.WriteString("func (Null) MarshalJSONTo(enc *jsontext.Encoder) error {\n")
	b.WriteString("\treturn enc.WriteToken(jsontext.Null)\n")
	b.WriteString("}\n\n")

	b.WriteString("func (n *Null) UnmarshalJSON(data []byte) error {\n")
	b.WriteString("\tvar value jsontext.Value\n")
	b.WriteString("\tif err := json.Unmarshal(data, &value); err != nil {\n\t\treturn err\n\t}\n")
	b.WriteString("\tif value.Kind() != 'n' {\n")
	b.WriteString("\t\treturn errors.New(\"Null: expected null\")\n\t}\n")
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n\n")

	b.WriteString("func (n *Null) UnmarshalJSONFrom(dec *jsontext.Decoder) error {\n")
	b.WriteString("\tvalue, err := dec.ReadValue()\n")
	b.WriteString("\tif err != nil {\n\t\treturn err\n\t}\n")
	b.WriteString("\treturn n.UnmarshalJSON(value)\n")
	b.WriteString("}\n\n")

	return nil
}

func (g *generator) needsUnionHelpers() bool {
	return len(g.unionDefs) > 0
}

func (g *generator) renderUnionHelpers(imports *fileImports) string {
	imports.add("github.com/go-json-experiment/json")
	imports.add("github.com/go-json-experiment/json/jsontext")

	var b strings.Builder
	b.WriteString("const (\n")
	b.WriteString("\tunionKindNull uint8 = 1 << iota\n")
	b.WriteString("\tunionKindBool\n")
	b.WriteString("\tunionKindString\n")
	b.WriteString("\tunionKindNumber\n")
	b.WriteString("\tunionKindObject\n")
	b.WriteString("\tunionKindArray\n")
	b.WriteString(")\n\n")

	b.WriteString("func unionKindMatches(kind jsontext.Kind, mask uint8) bool {\n")
	b.WriteString("\tswitch kind {\n")
	b.WriteString("\tcase 'n':\n\t\treturn mask&unionKindNull != 0\n")
	b.WriteString("\tcase 't', 'f':\n\t\treturn mask&unionKindBool != 0\n")
	b.WriteString("\tcase '\"':\n\t\treturn mask&unionKindString != 0\n")
	b.WriteString("\tcase '0':\n\t\treturn mask&unionKindNumber != 0\n")
	b.WriteString("\tcase '{':\n\t\treturn mask&unionKindObject != 0\n")
	b.WriteString("\tcase '[':\n\t\treturn mask&unionKindArray != 0\n")
	b.WriteString("\tdefault:\n\t\treturn false\n\t}\n")
	b.WriteString("}\n\n")

	b.WriteString("func decodeObject(value jsontext.Value) (map[string]jsontext.Value, error) {\n")
	b.WriteString("\tvar obj map[string]jsontext.Value\n")
	b.WriteString("\tif err := json.Unmarshal(value, &obj); err != nil {\n\t\treturn nil, err\n\t}\n")
	b.WriteString("\treturn obj, nil\n")
	b.WriteString("}\n\n")

	b.WriteString("func objectFieldEquals(obj map[string]jsontext.Value, name string, want string) bool {\n")
	b.WriteString("\tvalue, ok := obj[name]\n")
	b.WriteString("\tif !ok {\n\t\treturn false\n\t}\n")
	b.WriteString("\tvar got string\n")
	b.WriteString("\tif err := json.Unmarshal(value, &got); err != nil {\n\t\treturn false\n\t}\n")
	b.WriteString("\treturn got == want\n")
	b.WriteString("}\n\n")

	return b.String()
}
